// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.5.0
// source: common/entity.proto

/* eslint-disable */
import { PropType } from "./enum";

export const protobufPackage = "common";

/** 会话信息 */
export interface Session {
  $type: "common.Session";
  /** 消息ID */
  messageId: number;
  /** 序列号 */
  sequence: number;
  /** 时间戳 */
  timestamp: bigint;
  /** 版本号 */
  version: string;
}

/** 基础请求 */
export interface BaseRequest {
  $type: "common.BaseRequest";
  /** 会话信息 */
  session?:
    | Session
    | undefined;
  /** 消息内容 */
  payload: Uint8Array;
}

/** 基础响应 */
export interface BaseResponse {
  $type: "common.BaseResponse";
  /** 会话信息 */
  session?:
    | Session
    | undefined;
  /** 错误码 */
  errorCode: number;
  /** 错误信息 */
  errorMsg: string;
  /** 消息负载 */
  payload: Uint8Array;
}

/** 用户信息 */
export interface UserInfo {
  $type: "common.UserInfo";
  /** 用户ID */
  userId: bigint;
  /** 用户名 */
  username: string;
  /** 等级 */
  level: number;
  /** 经验值 */
  exp: bigint;
  /** 金币 */
  gold: bigint;
  /** VIP等级 */
  vipLevel: number;
  /** 生命值 */
  hp: number;
  /** 攻击力 */
  attack: number;
  /** 防御力 */
  defense: number;
  /** 创建时间 */
  createTime: bigint;
  /** 最后登录时间 */
  loginTime: bigint;
}

/** 卡牌信息 */
export interface CardInfo {
  $type: "common.CardInfo";
  /** 卡牌ID */
  cardId: bigint;
  /** 卡牌类型 */
  cardType: number;
  /** 等级 */
  level: number;
  /** 经验值 */
  exp: bigint;
  /** 品质 */
  quality: number;
  /** 星级 */
  star: number;
  /** 获得时间 */
  createTime: bigint;
  /** 战力 */
  power: number;
}

/** 物品信息 */
export interface ItemInfo {
  $type: "common.ItemInfo";
  itemId: number;
  count: number;
  slot: number;
}

/** 背包信息 */
export interface BagInfo {
  $type: "common.BagInfo";
  bagType: number;
  size: number;
  items: ItemInfo[];
}

/** 邮件信息 */
export interface MailInfo {
  $type: "common.MailInfo";
  /** 邮件ID */
  id: bigint;
  /** 标题 */
  title: string;
  /** 内容 */
  content: string;
  /** 附件物品 */
  items: ItemInfo[];
  /** 邮件类型 */
  mailType: number;
  /** 邮件状态 */
  status: number;
  /** 创建时间 */
  createTime: bigint;
  /** 过期时间 */
  expireTime: bigint;
  /** 模板ID */
  templateId: bigint;
  /** 发送者ID */
  senderId: bigint;
  /** 发送者名称 */
  senderName: string;
}

/** 邮件模板信息 */
export interface MailTemplateInfo {
  $type: "common.MailTemplateInfo";
  /** 模板ID */
  id: bigint;
  /** 标题 */
  title: string;
  /** 内容 */
  content: string;
  /** 附件物品 */
  items: ItemInfo[];
  /** 邮件类型 */
  mailType: number;
  /** 创建时间 */
  createTime: bigint;
  /** 过期时间 */
  expireTime: bigint;
}

/** 用户资源信息 */
export interface ResourceInfo {
  $type: "common.ResourceInfo";
  /** 资源类型 */
  type: number;
  /** 资源数量 */
  amount: number;
}

/** 伙伴基本信息 */
export interface PartnerBaseInfo {
  $type: "common.PartnerBaseInfo";
  /** 伙伴ID */
  partnerId: bigint;
  /** 单位ID */
  unitId: number;
  /** 等级 */
  level: number;
  /** 经验 */
  exp: number;
  /** 品质 */
  quality: number;
  /** 星级 */
  star: number;
  /** 创建时间 */
  createTime: bigint;
  /** 种族 */
  race: number;
  /** 特长/职业 */
  forte: number;
  /** 属性列表 */
  properties: PropertyInfo[];
}

/** 伙伴完整信息 */
export interface PartnerInfo {
  $type: "common.PartnerInfo";
  /** 基本信息 */
  baseInfo?:
    | PartnerBaseInfo
    | undefined;
  /** 状态 (1:可解锁, 2:已解锁, 3:未解锁) */
  state: number;
  /** 拥有的碎片数量 */
  fragmentCount: number;
  /** 解锁所需的碎片数量 */
  fragmentNeed: number;
  /** 是否可以升级 */
  canLevelUp: boolean;
  /** 是否可以升星 */
  canStarUp: boolean;
  /** 升级消耗 */
  levelUpCost: ItemCost[];
  /** 升星消耗 */
  starUpCost: ItemCost[];
}

/** 属性信息 */
export interface PropertyInfo {
  $type: "common.PropertyInfo";
  /** 属性ID */
  propId: PropType;
  /** 基础值 */
  value: number;
  /** 额外值(装备、星级加成等) */
  extra: number;
}

/** 属性变化 */
export interface PropertyChange {
  $type: "common.PropertyChange";
  /** 属性ID */
  propId: PropType;
  /** 变化值 */
  value: number;
}

/** 物品消耗 */
export interface ItemCost {
  $type: "common.ItemCost";
  /** 物品ID */
  itemId: number;
  /** 数量 */
  count: number;
}

export const Session: MessageFns<Session, "common.Session"> = { $type: "common.Session" as const };

export const BaseRequest: MessageFns<BaseRequest, "common.BaseRequest"> = { $type: "common.BaseRequest" as const };

export const BaseResponse: MessageFns<BaseResponse, "common.BaseResponse"> = { $type: "common.BaseResponse" as const };

export const UserInfo: MessageFns<UserInfo, "common.UserInfo"> = { $type: "common.UserInfo" as const };

export const CardInfo: MessageFns<CardInfo, "common.CardInfo"> = { $type: "common.CardInfo" as const };

export const ItemInfo: MessageFns<ItemInfo, "common.ItemInfo"> = { $type: "common.ItemInfo" as const };

export const BagInfo: MessageFns<BagInfo, "common.BagInfo"> = { $type: "common.BagInfo" as const };

export const MailInfo: MessageFns<MailInfo, "common.MailInfo"> = { $type: "common.MailInfo" as const };

export const MailTemplateInfo: MessageFns<MailTemplateInfo, "common.MailTemplateInfo"> = {
  $type: "common.MailTemplateInfo" as const,
};

export const ResourceInfo: MessageFns<ResourceInfo, "common.ResourceInfo"> = { $type: "common.ResourceInfo" as const };

export const PartnerBaseInfo: MessageFns<PartnerBaseInfo, "common.PartnerBaseInfo"> = {
  $type: "common.PartnerBaseInfo" as const,
};

export const PartnerInfo: MessageFns<PartnerInfo, "common.PartnerInfo"> = { $type: "common.PartnerInfo" as const };

export const PropertyInfo: MessageFns<PropertyInfo, "common.PropertyInfo"> = { $type: "common.PropertyInfo" as const };

export const PropertyChange: MessageFns<PropertyChange, "common.PropertyChange"> = {
  $type: "common.PropertyChange" as const,
};

export const ItemCost: MessageFns<ItemCost, "common.ItemCost"> = { $type: "common.ItemCost" as const };

export interface MessageFns<T, V extends string> {
  readonly $type: V;
}
