// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: common/enum.proto

/* eslint-disable */

export const protobufPackage = "common";

/** 背包类型 */
export enum BagType {
  BAG_TYPE_NONE = 0,
  /** BAG_TYPE_MAIN - 主背包 */
  BAG_TYPE_MAIN = 1,
  /** BAG_TYPE_STORAGE - 仓库 */
  BAG_TYPE_STORAGE = 2,
  /** BAG_TYPE_EQUIP - 装备栏 */
  BAG_TYPE_EQUIP = 3,
  UNRECOGNIZED = -1,
}

export function bagTypeFromJSON(object: any): BagType {
  switch (object) {
    case 0:
    case "BAG_TYPE_NONE":
      return BagType.BAG_TYPE_NONE;
    case 1:
    case "BAG_TYPE_MAIN":
      return BagType.BAG_TYPE_MAIN;
    case 2:
    case "BAG_TYPE_STORAGE":
      return BagType.BAG_TYPE_STORAGE;
    case 3:
    case "BAG_TYPE_EQUIP":
      return BagType.BAG_TYPE_EQUIP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BagType.UNRECOGNIZED;
  }
}

export function bagTypeToJSON(object: BagType): string {
  switch (object) {
    case BagType.BAG_TYPE_NONE:
      return "BAG_TYPE_NONE";
    case BagType.BAG_TYPE_MAIN:
      return "BAG_TYPE_MAIN";
    case BagType.BAG_TYPE_STORAGE:
      return "BAG_TYPE_STORAGE";
    case BagType.BAG_TYPE_EQUIP:
      return "BAG_TYPE_EQUIP";
    case BagType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 格子状态 */
export enum SlotState {
  SLOT_STATE_NONE = 0,
  /** SLOT_STATE_EMPTY - 空格子 */
  SLOT_STATE_EMPTY = 1,
  /** SLOT_STATE_NORMAL - 正常 */
  SLOT_STATE_NORMAL = 2,
  /** SLOT_STATE_LOCKED - 锁定 */
  SLOT_STATE_LOCKED = 3,
  UNRECOGNIZED = -1,
}

export function slotStateFromJSON(object: any): SlotState {
  switch (object) {
    case 0:
    case "SLOT_STATE_NONE":
      return SlotState.SLOT_STATE_NONE;
    case 1:
    case "SLOT_STATE_EMPTY":
      return SlotState.SLOT_STATE_EMPTY;
    case 2:
    case "SLOT_STATE_NORMAL":
      return SlotState.SLOT_STATE_NORMAL;
    case 3:
    case "SLOT_STATE_LOCKED":
      return SlotState.SLOT_STATE_LOCKED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SlotState.UNRECOGNIZED;
  }
}

export function slotStateToJSON(object: SlotState): string {
  switch (object) {
    case SlotState.SLOT_STATE_NONE:
      return "SLOT_STATE_NONE";
    case SlotState.SLOT_STATE_EMPTY:
      return "SLOT_STATE_EMPTY";
    case SlotState.SLOT_STATE_NORMAL:
      return "SLOT_STATE_NORMAL";
    case SlotState.SLOT_STATE_LOCKED:
      return "SLOT_STATE_LOCKED";
    case SlotState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 变化类型 */
export enum ChangeType {
  CHANGE_TYPE_NONE = 0,
  /** CHANGE_TYPE_ADD - 增加 */
  CHANGE_TYPE_ADD = 1,
  /** CHANGE_TYPE_REDUCE - 减少 */
  CHANGE_TYPE_REDUCE = 2,
  /** CHANGE_TYPE_USE - 使用 */
  CHANGE_TYPE_USE = 3,
  /** CHANGE_TYPE_COMPOSE - 合成 */
  CHANGE_TYPE_COMPOSE = 4,
  /** CHANGE_TYPE_DECOMPOSE - 分解 */
  CHANGE_TYPE_DECOMPOSE = 5,
  UNRECOGNIZED = -1,
}

export function changeTypeFromJSON(object: any): ChangeType {
  switch (object) {
    case 0:
    case "CHANGE_TYPE_NONE":
      return ChangeType.CHANGE_TYPE_NONE;
    case 1:
    case "CHANGE_TYPE_ADD":
      return ChangeType.CHANGE_TYPE_ADD;
    case 2:
    case "CHANGE_TYPE_REDUCE":
      return ChangeType.CHANGE_TYPE_REDUCE;
    case 3:
    case "CHANGE_TYPE_USE":
      return ChangeType.CHANGE_TYPE_USE;
    case 4:
    case "CHANGE_TYPE_COMPOSE":
      return ChangeType.CHANGE_TYPE_COMPOSE;
    case 5:
    case "CHANGE_TYPE_DECOMPOSE":
      return ChangeType.CHANGE_TYPE_DECOMPOSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChangeType.UNRECOGNIZED;
  }
}

export function changeTypeToJSON(object: ChangeType): string {
  switch (object) {
    case ChangeType.CHANGE_TYPE_NONE:
      return "CHANGE_TYPE_NONE";
    case ChangeType.CHANGE_TYPE_ADD:
      return "CHANGE_TYPE_ADD";
    case ChangeType.CHANGE_TYPE_REDUCE:
      return "CHANGE_TYPE_REDUCE";
    case ChangeType.CHANGE_TYPE_USE:
      return "CHANGE_TYPE_USE";
    case ChangeType.CHANGE_TYPE_COMPOSE:
      return "CHANGE_TYPE_COMPOSE";
    case ChangeType.CHANGE_TYPE_DECOMPOSE:
      return "CHANGE_TYPE_DECOMPOSE";
    case ChangeType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 变化来源 */
export enum ChangeSource {
  SOURCE_NONE = 0,
  /** SOURCE_INIT - 初始化 */
  SOURCE_INIT = 1,
  /** SOURCE_REWARD - 奖励 */
  SOURCE_REWARD = 2,
  /** SOURCE_USE - 使用 */
  SOURCE_USE = 3,
  /** SOURCE_COMPOSE - 合成 */
  SOURCE_COMPOSE = 4,
  /** SOURCE_DECOMPOSE - 分解 */
  SOURCE_DECOMPOSE = 5,
  /** SOURCE_TRADE - 交易 */
  SOURCE_TRADE = 6,
  /** SOURCE_MAIL - 邮件 */
  SOURCE_MAIL = 7,
  UNRECOGNIZED = -1,
}

export function changeSourceFromJSON(object: any): ChangeSource {
  switch (object) {
    case 0:
    case "SOURCE_NONE":
      return ChangeSource.SOURCE_NONE;
    case 1:
    case "SOURCE_INIT":
      return ChangeSource.SOURCE_INIT;
    case 2:
    case "SOURCE_REWARD":
      return ChangeSource.SOURCE_REWARD;
    case 3:
    case "SOURCE_USE":
      return ChangeSource.SOURCE_USE;
    case 4:
    case "SOURCE_COMPOSE":
      return ChangeSource.SOURCE_COMPOSE;
    case 5:
    case "SOURCE_DECOMPOSE":
      return ChangeSource.SOURCE_DECOMPOSE;
    case 6:
    case "SOURCE_TRADE":
      return ChangeSource.SOURCE_TRADE;
    case 7:
    case "SOURCE_MAIL":
      return ChangeSource.SOURCE_MAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChangeSource.UNRECOGNIZED;
  }
}

export function changeSourceToJSON(object: ChangeSource): string {
  switch (object) {
    case ChangeSource.SOURCE_NONE:
      return "SOURCE_NONE";
    case ChangeSource.SOURCE_INIT:
      return "SOURCE_INIT";
    case ChangeSource.SOURCE_REWARD:
      return "SOURCE_REWARD";
    case ChangeSource.SOURCE_USE:
      return "SOURCE_USE";
    case ChangeSource.SOURCE_COMPOSE:
      return "SOURCE_COMPOSE";
    case ChangeSource.SOURCE_DECOMPOSE:
      return "SOURCE_DECOMPOSE";
    case ChangeSource.SOURCE_TRADE:
      return "SOURCE_TRADE";
    case ChangeSource.SOURCE_MAIL:
      return "SOURCE_MAIL";
    case ChangeSource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 效果类型 */
export enum EffectType {
  EFFECT_TYPE_NONE = 0,
  /** EFFECT_TYPE_EXP - 经验 */
  EFFECT_TYPE_EXP = 1,
  /** EFFECT_TYPE_GOLD - 金币 */
  EFFECT_TYPE_GOLD = 2,
  /** EFFECT_TYPE_DIAMOND - 钻石 */
  EFFECT_TYPE_DIAMOND = 3,
  /** EFFECT_TYPE_PROP - 属性 */
  EFFECT_TYPE_PROP = 4,
  UNRECOGNIZED = -1,
}

export function effectTypeFromJSON(object: any): EffectType {
  switch (object) {
    case 0:
    case "EFFECT_TYPE_NONE":
      return EffectType.EFFECT_TYPE_NONE;
    case 1:
    case "EFFECT_TYPE_EXP":
      return EffectType.EFFECT_TYPE_EXP;
    case 2:
    case "EFFECT_TYPE_GOLD":
      return EffectType.EFFECT_TYPE_GOLD;
    case 3:
    case "EFFECT_TYPE_DIAMOND":
      return EffectType.EFFECT_TYPE_DIAMOND;
    case 4:
    case "EFFECT_TYPE_PROP":
      return EffectType.EFFECT_TYPE_PROP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EffectType.UNRECOGNIZED;
  }
}

export function effectTypeToJSON(object: EffectType): string {
  switch (object) {
    case EffectType.EFFECT_TYPE_NONE:
      return "EFFECT_TYPE_NONE";
    case EffectType.EFFECT_TYPE_EXP:
      return "EFFECT_TYPE_EXP";
    case EffectType.EFFECT_TYPE_GOLD:
      return "EFFECT_TYPE_GOLD";
    case EffectType.EFFECT_TYPE_DIAMOND:
      return "EFFECT_TYPE_DIAMOND";
    case EffectType.EFFECT_TYPE_PROP:
      return "EFFECT_TYPE_PROP";
    case EffectType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 品质 */
export enum Quality {
  QUALITY_NONE = 0,
  /** QUALITY_WHITE - 白色/普通 */
  QUALITY_WHITE = 1,
  /** QUALITY_GREEN - 绿色/优秀 */
  QUALITY_GREEN = 2,
  /** QUALITY_BLUE - 蓝色/精良 */
  QUALITY_BLUE = 3,
  /** QUALITY_PURPLE - 紫色/史诗 */
  QUALITY_PURPLE = 4,
  /** QUALITY_ORANGE - 橙色/传说 */
  QUALITY_ORANGE = 5,
  /** QUALITY_RED - 红色/神话 */
  QUALITY_RED = 6,
  UNRECOGNIZED = -1,
}

export function qualityFromJSON(object: any): Quality {
  switch (object) {
    case 0:
    case "QUALITY_NONE":
      return Quality.QUALITY_NONE;
    case 1:
    case "QUALITY_WHITE":
      return Quality.QUALITY_WHITE;
    case 2:
    case "QUALITY_GREEN":
      return Quality.QUALITY_GREEN;
    case 3:
    case "QUALITY_BLUE":
      return Quality.QUALITY_BLUE;
    case 4:
    case "QUALITY_PURPLE":
      return Quality.QUALITY_PURPLE;
    case 5:
    case "QUALITY_ORANGE":
      return Quality.QUALITY_ORANGE;
    case 6:
    case "QUALITY_RED":
      return Quality.QUALITY_RED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Quality.UNRECOGNIZED;
  }
}

export function qualityToJSON(object: Quality): string {
  switch (object) {
    case Quality.QUALITY_NONE:
      return "QUALITY_NONE";
    case Quality.QUALITY_WHITE:
      return "QUALITY_WHITE";
    case Quality.QUALITY_GREEN:
      return "QUALITY_GREEN";
    case Quality.QUALITY_BLUE:
      return "QUALITY_BLUE";
    case Quality.QUALITY_PURPLE:
      return "QUALITY_PURPLE";
    case Quality.QUALITY_ORANGE:
      return "QUALITY_ORANGE";
    case Quality.QUALITY_RED:
      return "QUALITY_RED";
    case Quality.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 排序规则 */
export enum SortRule {
  SORT_RULE_NONE = 0,
  /** SORT_RULE_TYPE - 按类型 */
  SORT_RULE_TYPE = 1,
  /** SORT_RULE_QUALITY - 按品质 */
  SORT_RULE_QUALITY = 2,
  /** SORT_RULE_LEVEL - 按等级 */
  SORT_RULE_LEVEL = 3,
  /** SORT_RULE_COUNT - 按数量 */
  SORT_RULE_COUNT = 4,
  /** SORT_RULE_TIME - 按时间 */
  SORT_RULE_TIME = 5,
  UNRECOGNIZED = -1,
}

export function sortRuleFromJSON(object: any): SortRule {
  switch (object) {
    case 0:
    case "SORT_RULE_NONE":
      return SortRule.SORT_RULE_NONE;
    case 1:
    case "SORT_RULE_TYPE":
      return SortRule.SORT_RULE_TYPE;
    case 2:
    case "SORT_RULE_QUALITY":
      return SortRule.SORT_RULE_QUALITY;
    case 3:
    case "SORT_RULE_LEVEL":
      return SortRule.SORT_RULE_LEVEL;
    case 4:
    case "SORT_RULE_COUNT":
      return SortRule.SORT_RULE_COUNT;
    case 5:
    case "SORT_RULE_TIME":
      return SortRule.SORT_RULE_TIME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SortRule.UNRECOGNIZED;
  }
}

export function sortRuleToJSON(object: SortRule): string {
  switch (object) {
    case SortRule.SORT_RULE_NONE:
      return "SORT_RULE_NONE";
    case SortRule.SORT_RULE_TYPE:
      return "SORT_RULE_TYPE";
    case SortRule.SORT_RULE_QUALITY:
      return "SORT_RULE_QUALITY";
    case SortRule.SORT_RULE_LEVEL:
      return "SORT_RULE_LEVEL";
    case SortRule.SORT_RULE_COUNT:
      return "SORT_RULE_COUNT";
    case SortRule.SORT_RULE_TIME:
      return "SORT_RULE_TIME";
    case SortRule.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 使用限制类型 */
export enum UseLimit {
  USE_LIMIT_NONE = 0,
  /** USE_LIMIT_LEVEL - 等级限制 */
  USE_LIMIT_LEVEL = 1,
  /** USE_LIMIT_VIP - VIP等级限制 */
  USE_LIMIT_VIP = 2,
  /** USE_LIMIT_TIME - 时间限制 */
  USE_LIMIT_TIME = 3,
  /** USE_LIMIT_COUNT - 次数限制 */
  USE_LIMIT_COUNT = 4,
  /** USE_LIMIT_DAILY - 每日限制 */
  USE_LIMIT_DAILY = 5,
  /** USE_LIMIT_WEEKLY - 每周限制 */
  USE_LIMIT_WEEKLY = 6,
  UNRECOGNIZED = -1,
}

export function useLimitFromJSON(object: any): UseLimit {
  switch (object) {
    case 0:
    case "USE_LIMIT_NONE":
      return UseLimit.USE_LIMIT_NONE;
    case 1:
    case "USE_LIMIT_LEVEL":
      return UseLimit.USE_LIMIT_LEVEL;
    case 2:
    case "USE_LIMIT_VIP":
      return UseLimit.USE_LIMIT_VIP;
    case 3:
    case "USE_LIMIT_TIME":
      return UseLimit.USE_LIMIT_TIME;
    case 4:
    case "USE_LIMIT_COUNT":
      return UseLimit.USE_LIMIT_COUNT;
    case 5:
    case "USE_LIMIT_DAILY":
      return UseLimit.USE_LIMIT_DAILY;
    case 6:
    case "USE_LIMIT_WEEKLY":
      return UseLimit.USE_LIMIT_WEEKLY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UseLimit.UNRECOGNIZED;
  }
}

export function useLimitToJSON(object: UseLimit): string {
  switch (object) {
    case UseLimit.USE_LIMIT_NONE:
      return "USE_LIMIT_NONE";
    case UseLimit.USE_LIMIT_LEVEL:
      return "USE_LIMIT_LEVEL";
    case UseLimit.USE_LIMIT_VIP:
      return "USE_LIMIT_VIP";
    case UseLimit.USE_LIMIT_TIME:
      return "USE_LIMIT_TIME";
    case UseLimit.USE_LIMIT_COUNT:
      return "USE_LIMIT_COUNT";
    case UseLimit.USE_LIMIT_DAILY:
      return "USE_LIMIT_DAILY";
    case UseLimit.USE_LIMIT_WEEKLY:
      return "USE_LIMIT_WEEKLY";
    case UseLimit.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 道具类型 */
export enum PropType {
  PROP_TYPE_NONE = 0,
  /** PROP_TYPE_HP - 生命值 */
  PROP_TYPE_HP = 1,
  /** PROP_TYPE_ATTACK - 攻击力 */
  PROP_TYPE_ATTACK = 2,
  /** PROP_TYPE_DEFENSE - 防御力 */
  PROP_TYPE_DEFENSE = 3,
  /** PROP_TYPE_SPEED - 速度 */
  PROP_TYPE_SPEED = 4,
  /** PROP_TYPE_CRIT - 暴击 */
  PROP_TYPE_CRIT = 5,
  /** PROP_TYPE_CRIT_DMG - 暴击伤害 */
  PROP_TYPE_CRIT_DMG = 6,
  UNRECOGNIZED = -1,
}

export function propTypeFromJSON(object: any): PropType {
  switch (object) {
    case 0:
    case "PROP_TYPE_NONE":
      return PropType.PROP_TYPE_NONE;
    case 1:
    case "PROP_TYPE_HP":
      return PropType.PROP_TYPE_HP;
    case 2:
    case "PROP_TYPE_ATTACK":
      return PropType.PROP_TYPE_ATTACK;
    case 3:
    case "PROP_TYPE_DEFENSE":
      return PropType.PROP_TYPE_DEFENSE;
    case 4:
    case "PROP_TYPE_SPEED":
      return PropType.PROP_TYPE_SPEED;
    case 5:
    case "PROP_TYPE_CRIT":
      return PropType.PROP_TYPE_CRIT;
    case 6:
    case "PROP_TYPE_CRIT_DMG":
      return PropType.PROP_TYPE_CRIT_DMG;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PropType.UNRECOGNIZED;
  }
}

export function propTypeToJSON(object: PropType): string {
  switch (object) {
    case PropType.PROP_TYPE_NONE:
      return "PROP_TYPE_NONE";
    case PropType.PROP_TYPE_HP:
      return "PROP_TYPE_HP";
    case PropType.PROP_TYPE_ATTACK:
      return "PROP_TYPE_ATTACK";
    case PropType.PROP_TYPE_DEFENSE:
      return "PROP_TYPE_DEFENSE";
    case PropType.PROP_TYPE_SPEED:
      return "PROP_TYPE_SPEED";
    case PropType.PROP_TYPE_CRIT:
      return "PROP_TYPE_CRIT";
    case PropType.PROP_TYPE_CRIT_DMG:
      return "PROP_TYPE_CRIT_DMG";
    case PropType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 装备位置 */
export enum EquipSlot {
  EQUIP_SLOT_NONE = 0,
  /** EQUIP_SLOT_WEAPON - 武器 */
  EQUIP_SLOT_WEAPON = 1,
  /** EQUIP_SLOT_ARMOR - 护甲 */
  EQUIP_SLOT_ARMOR = 2,
  /** EQUIP_SLOT_HELMET - 头盔 */
  EQUIP_SLOT_HELMET = 3,
  /** EQUIP_SLOT_NECKLACE - 项链 */
  EQUIP_SLOT_NECKLACE = 4,
  /** EQUIP_SLOT_RING - 戒指 */
  EQUIP_SLOT_RING = 5,
  /** EQUIP_SLOT_BELT - 腰带 */
  EQUIP_SLOT_BELT = 6,
  UNRECOGNIZED = -1,
}

export function equipSlotFromJSON(object: any): EquipSlot {
  switch (object) {
    case 0:
    case "EQUIP_SLOT_NONE":
      return EquipSlot.EQUIP_SLOT_NONE;
    case 1:
    case "EQUIP_SLOT_WEAPON":
      return EquipSlot.EQUIP_SLOT_WEAPON;
    case 2:
    case "EQUIP_SLOT_ARMOR":
      return EquipSlot.EQUIP_SLOT_ARMOR;
    case 3:
    case "EQUIP_SLOT_HELMET":
      return EquipSlot.EQUIP_SLOT_HELMET;
    case 4:
    case "EQUIP_SLOT_NECKLACE":
      return EquipSlot.EQUIP_SLOT_NECKLACE;
    case 5:
    case "EQUIP_SLOT_RING":
      return EquipSlot.EQUIP_SLOT_RING;
    case 6:
    case "EQUIP_SLOT_BELT":
      return EquipSlot.EQUIP_SLOT_BELT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EquipSlot.UNRECOGNIZED;
  }
}

export function equipSlotToJSON(object: EquipSlot): string {
  switch (object) {
    case EquipSlot.EQUIP_SLOT_NONE:
      return "EQUIP_SLOT_NONE";
    case EquipSlot.EQUIP_SLOT_WEAPON:
      return "EQUIP_SLOT_WEAPON";
    case EquipSlot.EQUIP_SLOT_ARMOR:
      return "EQUIP_SLOT_ARMOR";
    case EquipSlot.EQUIP_SLOT_HELMET:
      return "EQUIP_SLOT_HELMET";
    case EquipSlot.EQUIP_SLOT_NECKLACE:
      return "EQUIP_SLOT_NECKLACE";
    case EquipSlot.EQUIP_SLOT_RING:
      return "EQUIP_SLOT_RING";
    case EquipSlot.EQUIP_SLOT_BELT:
      return "EQUIP_SLOT_BELT";
    case EquipSlot.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 强化类型 */
export enum EnhanceType {
  ENHANCE_TYPE_NONE = 0,
  /** ENHANCE_TYPE_LEVEL - 等级强化 */
  ENHANCE_TYPE_LEVEL = 1,
  /** ENHANCE_TYPE_STAR - 升星 */
  ENHANCE_TYPE_STAR = 2,
  /** ENHANCE_TYPE_REFINE - 精炼 */
  ENHANCE_TYPE_REFINE = 3,
  /** ENHANCE_TYPE_REFORGE - 重铸 */
  ENHANCE_TYPE_REFORGE = 4,
  UNRECOGNIZED = -1,
}

export function enhanceTypeFromJSON(object: any): EnhanceType {
  switch (object) {
    case 0:
    case "ENHANCE_TYPE_NONE":
      return EnhanceType.ENHANCE_TYPE_NONE;
    case 1:
    case "ENHANCE_TYPE_LEVEL":
      return EnhanceType.ENHANCE_TYPE_LEVEL;
    case 2:
    case "ENHANCE_TYPE_STAR":
      return EnhanceType.ENHANCE_TYPE_STAR;
    case 3:
    case "ENHANCE_TYPE_REFINE":
      return EnhanceType.ENHANCE_TYPE_REFINE;
    case 4:
    case "ENHANCE_TYPE_REFORGE":
      return EnhanceType.ENHANCE_TYPE_REFORGE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EnhanceType.UNRECOGNIZED;
  }
}

export function enhanceTypeToJSON(object: EnhanceType): string {
  switch (object) {
    case EnhanceType.ENHANCE_TYPE_NONE:
      return "ENHANCE_TYPE_NONE";
    case EnhanceType.ENHANCE_TYPE_LEVEL:
      return "ENHANCE_TYPE_LEVEL";
    case EnhanceType.ENHANCE_TYPE_STAR:
      return "ENHANCE_TYPE_STAR";
    case EnhanceType.ENHANCE_TYPE_REFINE:
      return "ENHANCE_TYPE_REFINE";
    case EnhanceType.ENHANCE_TYPE_REFORGE:
      return "ENHANCE_TYPE_REFORGE";
    case EnhanceType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
