// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.5.0
// source: common/enum.proto

/* eslint-disable */

export const protobufPackage = "common";

export enum UnitType {
  UNIT_TYPE_HERO = 0,
  UNIT_TYPE_NPC = 1,
  UNIT_TYPE_MONSTER = 2,
  UNIT_TYPE_PARTNER = 4,
  UNRECOGNIZED = -1,
}

/** 背包类型 */
export enum BagType {
  BAG_TYPE_NONE = 0,
  /** BAG_TYPE_MAIN - 主背包 */
  BAG_TYPE_MAIN = 1,
  /** BAG_TYPE_STORAGE - 仓库 */
  BAG_TYPE_STORAGE = 2,
  /** BAG_TYPE_EQUIP - 装备栏 */
  BAG_TYPE_EQUIP = 3,
  UNRECOGNIZED = -1,
}

/** 物品类型 */
export enum ItemType {
  ITEM_TYPE_NONE = 0,
  /** ITEM_TYPE_RESOURCE - 资源 */
  ITEM_TYPE_RESOURCE = 1,
  /** ITEM_TYPE_NORMAL - 普通 */
  ITEM_TYPE_NORMAL = 2,
  /** ITEM_TYPE_EQUIP - 装备 */
  ITEM_TYPE_EQUIP = 3,
  /** ITEM_TYPE_PARTNER - 伙伴 */
  ITEM_TYPE_PARTNER = 4,
  /** ITEM_TYPE_PARTNER_FRAGMENT - 伙伴碎片 */
  ITEM_TYPE_PARTNER_FRAGMENT = 5,
  /** ITEM_TYPE_TREASURE - 宝箱 */
  ITEM_TYPE_TREASURE = 9,
  UNRECOGNIZED = -1,
}

/** 物品分类 */
export enum ItemCategory {
  ITEM_CATEGORY_NONE = 0,
  /** ITEM_CATEGORY_WEAPON - 武器 */
  ITEM_CATEGORY_WEAPON = 1,
  /** ITEM_CATEGORY_ARMOR - 防具 */
  ITEM_CATEGORY_ARMOR = 2,
  /** ITEM_CATEGORY_ACCESSORY - 饰品 */
  ITEM_CATEGORY_ACCESSORY = 3,
  /** ITEM_CATEGORY_POTION - 药水 */
  ITEM_CATEGORY_POTION = 4,
  /** ITEM_CATEGORY_SCROLL - 卷轴 */
  ITEM_CATEGORY_SCROLL = 5,
  /** ITEM_CATEGORY_MATERIAL - 材料 */
  ITEM_CATEGORY_MATERIAL = 6,
  /** ITEM_CATEGORY_QUEST - 任务 */
  ITEM_CATEGORY_QUEST = 7,
  /** ITEM_CATEGORY_OTHER - 其他 */
  ITEM_CATEGORY_OTHER = 8,
  UNRECOGNIZED = -1,
}

export enum SpecialItemID {
  SPECIAL_ITEM_ID_NONE = 0,
  /** SPECIAL_ITEM_ID_GOLD - 金币 */
  SPECIAL_ITEM_ID_GOLD = 1001,
  /** SPECIAL_ITEM_ID_EXP - 经验 */
  SPECIAL_ITEM_ID_EXP = 1005,
  UNRECOGNIZED = -1,
}

/** 格子状态 */
export enum SlotState {
  SLOT_STATE_NONE = 0,
  /** SLOT_STATE_EMPTY - 空格子 */
  SLOT_STATE_EMPTY = 1,
  /** SLOT_STATE_NORMAL - 正常 */
  SLOT_STATE_NORMAL = 2,
  /** SLOT_STATE_LOCKED - 锁定 */
  SLOT_STATE_LOCKED = 3,
  UNRECOGNIZED = -1,
}

/** 变化类型 */
export enum ChangeType {
  CHANGE_TYPE_NONE = 0,
  /** CHANGE_TYPE_ADD - 增加 */
  CHANGE_TYPE_ADD = 1,
  /** CHANGE_TYPE_REDUCE - 减少 */
  CHANGE_TYPE_REDUCE = 2,
  /** CHANGE_TYPE_USE - 使用 */
  CHANGE_TYPE_USE = 3,
  /** CHANGE_TYPE_COMPOSE - 合成 */
  CHANGE_TYPE_COMPOSE = 4,
  /** CHANGE_TYPE_DECOMPOSE - 分解 */
  CHANGE_TYPE_DECOMPOSE = 5,
  UNRECOGNIZED = -1,
}

/** 变化来源 */
export enum ChangeSource {
  SOURCE_NONE = 0,
  /** SOURCE_INIT - 初始化 */
  SOURCE_INIT = 1,
  /** SOURCE_REWARD - 奖励 */
  SOURCE_REWARD = 2,
  /** SOURCE_CREATE - 创建 */
  SOURCE_CREATE = 3,
  /** SOURCE_USE - 使用 */
  SOURCE_USE = 4,
  /** SOURCE_COMPOSE - 合成 */
  SOURCE_COMPOSE = 5,
  /** SOURCE_DECOMPOSE - 分解 */
  SOURCE_DECOMPOSE = 6,
  /** SOURCE_STACK - 堆叠 */
  SOURCE_STACK = 7,
  /** SOURCE_BATCH_REMOVE - 批量删除 */
  SOURCE_BATCH_REMOVE = 8,
  /** SOURCE_TRADE - 交易 */
  SOURCE_TRADE = 9,
  /** SOURCE_MAIL - 邮件 */
  SOURCE_MAIL = 10,
  /** SOURCE_GM - GM */
  SOURCE_GM = 11,
  /** SOURCE_REMOVE_GEM - 卸下宝石 */
  SOURCE_REMOVE_GEM = 12,
  /** SOURCE_UNEQUIP - 卸下装备 */
  SOURCE_UNEQUIP = 13,
  /** SOURCE_ENHANCE - 强化 */
  SOURCE_ENHANCE = 14,
  /** SOURCE_REFINE - 精炼 */
  SOURCE_REFINE = 15,
  /** SOURCE_REFORGE - 洗练 */
  SOURCE_REFORGE = 16,
  UNRECOGNIZED = -1,
}

/** 效果类型 */
export enum EffectType {
  EFFECT_TYPE_NONE = 0,
  /** EFFECT_TYPE_EXP - 经验 */
  EFFECT_TYPE_EXP = 1,
  /** EFFECT_TYPE_GOLD - 金币 */
  EFFECT_TYPE_GOLD = 2,
  /** EFFECT_TYPE_DIAMOND - 钻石 */
  EFFECT_TYPE_DIAMOND = 3,
  /** EFFECT_TYPE_PROP - 属性 */
  EFFECT_TYPE_PROP = 4,
  UNRECOGNIZED = -1,
}

/** 品质 */
export enum Quality {
  QUALITY_NONE = 0,
  /** QUALITY_WHITE - 白色/普通 */
  QUALITY_WHITE = 1,
  /** QUALITY_GREEN - 绿色/优秀 */
  QUALITY_GREEN = 2,
  /** QUALITY_BLUE - 蓝色/精良 */
  QUALITY_BLUE = 3,
  /** QUALITY_PURPLE - 紫色/史诗 */
  QUALITY_PURPLE = 4,
  /** QUALITY_ORANGE - 橙色/传说 */
  QUALITY_ORANGE = 5,
  /** QUALITY_RED - 红色/神话 */
  QUALITY_RED = 6,
  UNRECOGNIZED = -1,
}

/** 排序规则 */
export enum SortRule {
  SORT_RULE_NONE = 0,
  /** SORT_RULE_TYPE - 按类型 */
  SORT_RULE_TYPE = 1,
  /** SORT_RULE_QUALITY - 按品质 */
  SORT_RULE_QUALITY = 2,
  /** SORT_RULE_LEVEL - 按等级 */
  SORT_RULE_LEVEL = 3,
  /** SORT_RULE_COUNT - 按数量 */
  SORT_RULE_COUNT = 4,
  /** SORT_RULE_TIME - 按时间 */
  SORT_RULE_TIME = 5,
  UNRECOGNIZED = -1,
}

/** 使用限制类型 */
export enum UseLimit {
  USE_LIMIT_NONE = 0,
  /** USE_LIMIT_LEVEL - 等级限制 */
  USE_LIMIT_LEVEL = 1,
  /** USE_LIMIT_VIP - VIP等级限制 */
  USE_LIMIT_VIP = 2,
  /** USE_LIMIT_TIME - 时间限制 */
  USE_LIMIT_TIME = 3,
  /** USE_LIMIT_COUNT - 次数限制 */
  USE_LIMIT_COUNT = 4,
  /** USE_LIMIT_DAILY - 每日限制 */
  USE_LIMIT_DAILY = 5,
  /** USE_LIMIT_WEEKLY - 每周限制 */
  USE_LIMIT_WEEKLY = 6,
  UNRECOGNIZED = -1,
}

/** 通用属性类型 (用于玩家、伙伴等所有实体) */
export enum PropType {
  PROP_UNKNOWN = 0,
  /** PROP_HP - 基础属性 (100-199) */
  PROP_HP = 101,
  /** PROP_MP - 魔法值 */
  PROP_MP = 102,
  /** PROP_ATTACK - 攻击力 */
  PROP_ATTACK = 103,
  /** PROP_DEFENSE - 防御力 */
  PROP_DEFENSE = 104,
  /** PROP_SPEED - 速度 */
  PROP_SPEED = 105,
  /** PROP_HIT - 战斗属性 (200-299) */
  PROP_HIT = 201,
  /** PROP_DODGE - 闪避率 */
  PROP_DODGE = 202,
  /** PROP_CRIT_RATE - 暴击率 */
  PROP_CRIT_RATE = 203,
  /** PROP_CRIT_DMG - 暴击伤害 */
  PROP_CRIT_DMG = 204,
  /** PROP_BLOCK - 格挡率 */
  PROP_BLOCK = 205,
  /** PROP_PENETRATION - 穿透力 */
  PROP_PENETRATION = 206,
  /** PROP_HEAL_BOOST - 增益属性 (300-399) */
  PROP_HEAL_BOOST = 301,
  /** PROP_DMG_BOOST - 伤害加成 */
  PROP_DMG_BOOST = 302,
  /** PROP_DMG_REDUCTION - 伤害减免 */
  PROP_DMG_REDUCTION = 303,
  /** PROP_EXP_BOOST - 经验加成 */
  PROP_EXP_BOOST = 304,
  /** PROP_FIRE_RES - 抗性属性 (400-499) */
  PROP_FIRE_RES = 401,
  /** PROP_ICE_RES - 冰霜抗性 */
  PROP_ICE_RES = 402,
  /** PROP_LIGHTNING_RES - 雷电抗性 */
  PROP_LIGHTNING_RES = 403,
  /** PROP_POISON_RES - 毒素抗性 */
  PROP_POISON_RES = 404,
  /** PROP_GOLD_BOOST - 特殊属性 (500-599) */
  PROP_GOLD_BOOST = 501,
  /** PROP_ITEM_FIND - 物品发现率 */
  PROP_ITEM_FIND = 502,
  /** PROP_MOVEMENT_SPEED - 移动速度 */
  PROP_MOVEMENT_SPEED = 503,
  UNRECOGNIZED = -1,
}

/** 装备位置 */
export enum EquipSlot {
  EQUIP_SLOT_NONE = 0,
  /** EQUIP_SLOT_WEAPON - 武器 */
  EQUIP_SLOT_WEAPON = 1,
  /** EQUIP_SLOT_ARMOR - 护甲 */
  EQUIP_SLOT_ARMOR = 2,
  /** EQUIP_SLOT_HELMET - 头盔 */
  EQUIP_SLOT_HELMET = 3,
  /** EQUIP_SLOT_NECKLACE - 项链 */
  EQUIP_SLOT_NECKLACE = 4,
  /** EQUIP_SLOT_RING - 戒指 */
  EQUIP_SLOT_RING = 5,
  /** EQUIP_SLOT_BELT - 腰带 */
  EQUIP_SLOT_BELT = 6,
  UNRECOGNIZED = -1,
}

/** 强化类型 */
export enum EnhanceType {
  ENHANCE_TYPE_NONE = 0,
  /** ENHANCE_TYPE_LEVEL - 等级强化 */
  ENHANCE_TYPE_LEVEL = 1,
  /** ENHANCE_TYPE_STAR - 升星 */
  ENHANCE_TYPE_STAR = 2,
  /** ENHANCE_TYPE_REFINE - 精炼 */
  ENHANCE_TYPE_REFINE = 3,
  /** ENHANCE_TYPE_REFORGE - 重铸 */
  ENHANCE_TYPE_REFORGE = 4,
  UNRECOGNIZED = -1,
}

/** 物品标签 */
export enum ItemTag {
  ITEM_TAG_NONE = 0,
  /** ITEM_TAG_QUEST - 任务物品 */
  ITEM_TAG_QUEST = 1,
  /** ITEM_TAG_RARE - 稀有物品 */
  ITEM_TAG_RARE = 2,
  /** ITEM_TAG_TRADABLE - 可交易 */
  ITEM_TAG_TRADABLE = 3,
  /** ITEM_TAG_BIND - 绑定物品 */
  ITEM_TAG_BIND = 4,
  /** ITEM_TAG_EXPIRE - 限时物品 */
  ITEM_TAG_EXPIRE = 5,
  /** ITEM_TAG_STACK - 可堆叠 */
  ITEM_TAG_STACK = 6,
  /** ITEM_TAG_UNIQUE - 唯一物品 */
  ITEM_TAG_UNIQUE = 7,
  UNRECOGNIZED = -1,
}

/** 绑定类型 */
export enum BindType {
  /** BIND_TYPE_NONE - 未绑定 */
  BIND_TYPE_NONE = 0,
  /** BIND_TYPE_BIND - 已绑定 */
  BIND_TYPE_BIND = 1,
  UNRECOGNIZED = -1,
}

/** 合成结果类型 */
export enum ComposeResult {
  COMPOSE_RESULT_NONE = 0,
  /** COMPOSE_RESULT_SUCCESS - 成功 */
  COMPOSE_RESULT_SUCCESS = 1,
  /** COMPOSE_RESULT_FAIL - 失败但不消耗材料 */
  COMPOSE_RESULT_FAIL = 2,
  /** COMPOSE_RESULT_FAIL_CONSUME - 失败且消耗材料 */
  COMPOSE_RESULT_FAIL_CONSUME = 3,
  UNRECOGNIZED = -1,
}

/** 分解结果类型 */
export enum DecomposeResult {
  DECOMPOSE_RESULT_NONE = 0,
  /** DECOMPOSE_RESULT_NORMAL - 普通产出 */
  DECOMPOSE_RESULT_NORMAL = 1,
  /** DECOMPOSE_RESULT_EXTRA - 额外产出 */
  DECOMPOSE_RESULT_EXTRA = 2,
  /** DECOMPOSE_RESULT_CRITICAL - 暴击产出 */
  DECOMPOSE_RESULT_CRITICAL = 3,
  UNRECOGNIZED = -1,
}

/** 使用限制类型 */
export enum UseLimitType {
  /** USE_LIMIT_TYPE_NONE - 无限制 */
  USE_LIMIT_TYPE_NONE = 0,
  /** USE_LIMIT_TYPE_DAILY - 每日限制 */
  USE_LIMIT_TYPE_DAILY = 1,
  /** USE_LIMIT_TYPE_WEEKLY - 每周限制 */
  USE_LIMIT_TYPE_WEEKLY = 2,
  /** USE_LIMIT_TYPE_TOTAL - 总次数限制 */
  USE_LIMIT_TYPE_TOTAL = 3,
  UNRECOGNIZED = -1,
}

/** 装备槽位 */
export enum EquipSlotType {
  EQUIP_SLOT_TYPE_NONE = 0,
  /** EQUIP_SLOT_TYPE_WEAPON - 武器槽 */
  EQUIP_SLOT_TYPE_WEAPON = 1,
  /** EQUIP_SLOT_TYPE_HEAD - 头部槽 */
  EQUIP_SLOT_TYPE_HEAD = 2,
  /** EQUIP_SLOT_TYPE_BODY - 身体槽 */
  EQUIP_SLOT_TYPE_BODY = 3,
  /** EQUIP_SLOT_TYPE_HANDS - 手部槽 */
  EQUIP_SLOT_TYPE_HANDS = 4,
  /** EQUIP_SLOT_TYPE_FEET - 脚部槽 */
  EQUIP_SLOT_TYPE_FEET = 5,
  /** EQUIP_SLOT_TYPE_NECK - 项链槽 */
  EQUIP_SLOT_TYPE_NECK = 6,
  /** EQUIP_SLOT_TYPE_FINGER1 - 戒指槽1 */
  EQUIP_SLOT_TYPE_FINGER1 = 7,
  /** EQUIP_SLOT_TYPE_FINGER2 - 戒指槽2 */
  EQUIP_SLOT_TYPE_FINGER2 = 8,
  /** EQUIP_SLOT_TYPE_TRINKET - 饰品槽 */
  EQUIP_SLOT_TYPE_TRINKET = 9,
  UNRECOGNIZED = -1,
}

/** 装备属性类型 */
export enum EquipPropType {
  EQUIP_PROP_TYPE_NONE = 0,
  /** EQUIP_PROP_TYPE_ATK - 攻击力 */
  EQUIP_PROP_TYPE_ATK = 1,
  /** EQUIP_PROP_TYPE_DEF - 防御力 */
  EQUIP_PROP_TYPE_DEF = 2,
  /** EQUIP_PROP_TYPE_HP - 生命值 */
  EQUIP_PROP_TYPE_HP = 3,
  /** EQUIP_PROP_TYPE_MP - 魔法值 */
  EQUIP_PROP_TYPE_MP = 4,
  /** EQUIP_PROP_TYPE_CRIT_RATE - 暴击率 */
  EQUIP_PROP_TYPE_CRIT_RATE = 5,
  /** EQUIP_PROP_TYPE_CRIT_DMG - 暴击伤害 */
  EQUIP_PROP_TYPE_CRIT_DMG = 6,
  /** EQUIP_PROP_TYPE_SPEED - 速度 */
  EQUIP_PROP_TYPE_SPEED = 7,
  /** EQUIP_PROP_TYPE_DODGE - 闪避率 */
  EQUIP_PROP_TYPE_DODGE = 8,
  UNRECOGNIZED = -1,
}

/** 强化结果类型 */
export enum EnhanceResult {
  ENHANCE_RESULT_NONE = 0,
  /** ENHANCE_RESULT_SUCCESS - 成功 */
  ENHANCE_RESULT_SUCCESS = 1,
  /** ENHANCE_RESULT_FAIL - 失败但不降级 */
  ENHANCE_RESULT_FAIL = 2,
  /** ENHANCE_RESULT_FAIL_DOWN - 失败且降级 */
  ENHANCE_RESULT_FAIL_DOWN = 3,
  /** ENHANCE_RESULT_BREAK - 失败且装备破碎 */
  ENHANCE_RESULT_BREAK = 4,
  UNRECOGNIZED = -1,
}

/** 精炼结果类型 */
export enum RefineResult {
  REFINE_RESULT_NONE = 0,
  /** REFINE_RESULT_SUCCESS - 成功 */
  REFINE_RESULT_SUCCESS = 1,
  /** REFINE_RESULT_FAIL - 失败但不降级 */
  REFINE_RESULT_FAIL = 2,
  /** REFINE_RESULT_FAIL_DOWN - 失败且降级 */
  REFINE_RESULT_FAIL_DOWN = 3,
  /** REFINE_RESULT_BREAK - 失败且装备破碎 */
  REFINE_RESULT_BREAK = 4,
  UNRECOGNIZED = -1,
}

/** 洗练属性类型 */
export enum ReforgePropType {
  REFORGE_PROP_TYPE_NONE = 0,
  /** REFORGE_PROP_TYPE_FIXED - 固定属性 */
  REFORGE_PROP_TYPE_FIXED = 1,
  /** REFORGE_PROP_TYPE_RANDOM - 随机属性 */
  REFORGE_PROP_TYPE_RANDOM = 2,
  /** REFORGE_PROP_TYPE_SPECIAL - 特殊属性 */
  REFORGE_PROP_TYPE_SPECIAL = 3,
  UNRECOGNIZED = -1,
}

/** 洗练结果类型 */
export enum ReforgeResult {
  REFORGE_RESULT_NONE = 0,
  /** REFORGE_RESULT_SUCCESS - 成功 */
  REFORGE_RESULT_SUCCESS = 1,
  /** REFORGE_RESULT_FAIL - 失败 */
  REFORGE_RESULT_FAIL = 2,
  /** REFORGE_RESULT_PERFECT - 完美洗练 */
  REFORGE_RESULT_PERFECT = 3,
  UNRECOGNIZED = -1,
}

/** 宝石类型 */
export enum GemType {
  GEM_TYPE_NONE = 0,
  /** GEM_TYPE_ATTACK - 攻击宝石 */
  GEM_TYPE_ATTACK = 1,
  /** GEM_TYPE_DEFENSE - 防御宝石 */
  GEM_TYPE_DEFENSE = 2,
  /** GEM_TYPE_HEALTH - 生命宝石 */
  GEM_TYPE_HEALTH = 3,
  /** GEM_TYPE_CRIT - 暴击宝石 */
  GEM_TYPE_CRIT = 4,
  /** GEM_TYPE_SPEED - 速度宝石 */
  GEM_TYPE_SPEED = 5,
  /** GEM_TYPE_SPECIAL - 特殊宝石 */
  GEM_TYPE_SPECIAL = 6,
  UNRECOGNIZED = -1,
}

/** 宝石槽位状态 */
export enum GemSlotState {
  GEM_SLOT_STATE_NONE = 0,
  /** GEM_SLOT_STATE_EMPTY - 空槽位 */
  GEM_SLOT_STATE_EMPTY = 1,
  /** GEM_SLOT_STATE_OCCUPIED - 已镶嵌 */
  GEM_SLOT_STATE_OCCUPIED = 2,
  /** GEM_SLOT_STATE_LOCKED - 已锁定 */
  GEM_SLOT_STATE_LOCKED = 3,
  UNRECOGNIZED = -1,
}

/** 宝石操作结果 */
export enum GemResult {
  GEM_RESULT_NONE = 0,
  /** GEM_RESULT_SUCCESS - 成功 */
  GEM_RESULT_SUCCESS = 1,
  /** GEM_RESULT_FAIL - 失败 */
  GEM_RESULT_FAIL = 2,
  /** GEM_RESULT_BREAK - 宝石破碎 */
  GEM_RESULT_BREAK = 3,
  UNRECOGNIZED = -1,
}

/** 物品状态 */
export enum ItemState {
  ITEM_STATE_NONE = 0,
  /** ITEM_STATE_NORMAL - 正常 */
  ITEM_STATE_NORMAL = 1,
  /** ITEM_STATE_LOCKED - 锁定 */
  ITEM_STATE_LOCKED = 2,
  /** ITEM_STATE_TRADING - 交易中 */
  ITEM_STATE_TRADING = 3,
  /** ITEM_STATE_AUCTIONING - 拍卖中 */
  ITEM_STATE_AUCTIONING = 4,
  UNRECOGNIZED = -1,
}

/** 交易状态 */
export enum TradeState {
  TRADE_STATE_NONE = 0,
  /** TRADE_STATE_PENDING - 等待交易 */
  TRADE_STATE_PENDING = 1,
  /** TRADE_STATE_TRADING - 交易中 */
  TRADE_STATE_TRADING = 2,
  /** TRADE_STATE_COMPLETED - 交易完成 */
  TRADE_STATE_COMPLETED = 3,
  UNRECOGNIZED = -1,
}

/** 拍卖状态 */
export enum AuctionState {
  AUCTION_STATE_NONE = 0,
  /** AUCTION_STATE_ONGOING - 拍卖中 */
  AUCTION_STATE_ONGOING = 1,
  /** AUCTION_STATE_COMPLETED - 已成交 */
  AUCTION_STATE_COMPLETED = 2,
  /** AUCTION_STATE_CANCELLED - 已取消 */
  AUCTION_STATE_CANCELLED = 3,
  UNRECOGNIZED = -1,
}

/** 邮件类型 */
export enum MailType {
  MAIL_TYPE_NONE = 0,
  /** MAIL_TYPE_SYSTEM - 系统邮件 */
  MAIL_TYPE_SYSTEM = 1,
  /** MAIL_TYPE_PERSONAL - 个人邮件 */
  MAIL_TYPE_PERSONAL = 2,
  UNRECOGNIZED = -1,
}

/** 邮件状态 */
export enum MailStatus {
  MAIL_STATUS_NONE = 0,
  /** MAIL_STATUS_UNREAD - 未读 */
  MAIL_STATUS_UNREAD = 1,
  /** MAIL_STATUS_READ - 已读 */
  MAIL_STATUS_READ = 2,
  /** MAIL_STATUS_CLAIMED - 已领取 */
  MAIL_STATUS_CLAIMED = 3,
  /** MAIL_STATUS_DELETED - 已删除 */
  MAIL_STATUS_DELETED = 4,
  /** MAIL_STATUS_EXPIRED - 已过期 */
  MAIL_STATUS_EXPIRED = 5,
  UNRECOGNIZED = -1,
}

/** 资源类型 */
export enum ResourceType {
  RESOURCE_TYPE_NONE = 0,
  /** RESOURCE_TYPE_GOLD - 金币 */
  RESOURCE_TYPE_GOLD = 1,
  /** RESOURCE_TYPE_EXP - 经验 */
  RESOURCE_TYPE_EXP = 2,
  UNRECOGNIZED = -1,
}

/** 伙伴状态 */
export enum PartnerState {
  PARTNER_STATE_UNKNOWN = 0,
  /** PARTNER_STATE_AVAILABLE - 可解锁 */
  PARTNER_STATE_AVAILABLE = 1,
  /** PARTNER_STATE_UNLOCKED - 已解锁 */
  PARTNER_STATE_UNLOCKED = 2,
  /** PARTNER_STATE_LOCKED - 未解锁 */
  PARTNER_STATE_LOCKED = 3,
  UNRECOGNIZED = -1,
}

/** 伙伴种族 */
export enum PartnerRace {
  PARTNER_RACE_UNKNOWN = 0,
  /** PARTNER_RACE_HUMAN - 人类 */
  PARTNER_RACE_HUMAN = 1,
  /** PARTNER_RACE_ELF - 精灵 */
  PARTNER_RACE_ELF = 2,
  /** PARTNER_RACE_DWARF - 矮人 */
  PARTNER_RACE_DWARF = 3,
  /** PARTNER_RACE_ORC - 兽人 */
  PARTNER_RACE_ORC = 4,
  /** PARTNER_RACE_UNDEAD - 亡灵 */
  PARTNER_RACE_UNDEAD = 5,
  /** PARTNER_RACE_TAUREN - 牛头人 */
  PARTNER_RACE_TAUREN = 6,
  /** PARTNER_RACE_GNOME - 侏儒 */
  PARTNER_RACE_GNOME = 7,
  /** PARTNER_RACE_TROLL - 巨魔 */
  PARTNER_RACE_TROLL = 8,
  UNRECOGNIZED = -1,
}

/** 伙伴特长/职业 */
export enum PartnerForte {
  PARTNER_FORTE_UNKNOWN = 0,
  /** PARTNER_FORTE_WARRIOR - 战士 */
  PARTNER_FORTE_WARRIOR = 1,
  /** PARTNER_FORTE_MAGE - 法师 */
  PARTNER_FORTE_MAGE = 2,
  /** PARTNER_FORTE_PRIEST - 牧师 */
  PARTNER_FORTE_PRIEST = 3,
  /** PARTNER_FORTE_ROGUE - 盗贼 */
  PARTNER_FORTE_ROGUE = 4,
  /** PARTNER_FORTE_HUNTER - 猎人 */
  PARTNER_FORTE_HUNTER = 5,
  /** PARTNER_FORTE_PALADIN - 圣骑士 */
  PARTNER_FORTE_PALADIN = 6,
  /** PARTNER_FORTE_SHAMAN - 萨满 */
  PARTNER_FORTE_SHAMAN = 7,
  /** PARTNER_FORTE_DRUID - 德鲁伊 */
  PARTNER_FORTE_DRUID = 8,
  /** PARTNER_FORTE_WARLOCK - 术士 */
  PARTNER_FORTE_WARLOCK = 9,
  UNRECOGNIZED = -1,
}
