// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: common/message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

/** 消息ID定义 */
export enum MessageID {
  NONE = 0,
  /** C2L_LOGIN_REQUEST - 账号系统 (1-99) */
  C2L_LOGIN_REQUEST = 1,
  /** L2C_LOGIN_RESPONSE - 登录服务器到客户端的登录响应 */
  L2C_LOGIN_RESPONSE = 2,
  /** C2G_HEARTBEAT_REQUEST - 客户端到游戏服务器的心跳请求 */
  C2G_HEARTBEAT_REQUEST = 3,
  /** G2C_HEARTBEAT_RESPONSE - 游戏服务器到客户端的心跳响应 */
  G2C_HEARTBEAT_RESPONSE = 4,
  /** C2G_USER_INFO_REQUEST - 获取用户信息请求 */
  C2G_USER_INFO_REQUEST = 5,
  /** G2C_USER_INFO_RESPONSE - 获取用户信息响应 */
  G2C_USER_INFO_RESPONSE = 6,
  /** C2G_USER_CARDS_REQUEST - 卡牌系统 (100-199) */
  C2G_USER_CARDS_REQUEST = 100,
  /** G2C_USER_CARDS_RESPONSE - 获取用户卡牌响应 */
  G2C_USER_CARDS_RESPONSE = 101,
  /** C2G_BAG_INFO_REQUEST - 物品系统 (200-299) */
  C2G_BAG_INFO_REQUEST = 200,
  /** G2C_BAG_INFO_RESPONSE - 获取背包信息响应 */
  G2C_BAG_INFO_RESPONSE = 201,
  /** C2G_USE_ITEM_REQUEST - 使用物品请求 */
  C2G_USE_ITEM_REQUEST = 202,
  /** G2C_USE_ITEM_RESPONSE - 使用物品响应 */
  G2C_USE_ITEM_RESPONSE = 203,
  /** C2G_EXPAND_BAG_REQUEST - 扩展背包请求 */
  C2G_EXPAND_BAG_REQUEST = 204,
  /** G2C_EXPAND_BAG_RESPONSE - 扩展背包响应 */
  G2C_EXPAND_BAG_RESPONSE = 205,
  /** C2G_SORT_BAG_REQUEST - 整理背包请求 */
  C2G_SORT_BAG_REQUEST = 206,
  /** G2C_SORT_BAG_RESPONSE - 整理背包响应 */
  G2C_SORT_BAG_RESPONSE = 207,
  /** C2G_MOVE_ITEM_REQUEST - 移动物品请求 */
  C2G_MOVE_ITEM_REQUEST = 208,
  /** G2C_MOVE_ITEM_RESPONSE - 移动物品响应 */
  G2C_MOVE_ITEM_RESPONSE = 209,
  /** C2G_COMPOSE_ITEM_REQUEST - 物品合成请求 */
  C2G_COMPOSE_ITEM_REQUEST = 210,
  /** G2C_COMPOSE_ITEM_RESPONSE - 物品合成响应 */
  G2C_COMPOSE_ITEM_RESPONSE = 211,
  /** C2G_DECOMPOSE_ITEM_REQUEST - 物品分解请求 */
  C2G_DECOMPOSE_ITEM_REQUEST = 212,
  /** G2C_DECOMPOSE_ITEM_RESPONSE - 物品分解响应 */
  G2C_DECOMPOSE_ITEM_RESPONSE = 213,
  /** C2G_GM_COMMAND_REQUEST - GM系统 (300-399) */
  C2G_GM_COMMAND_REQUEST = 300,
  /** G2C_GM_COMMAND_RESPONSE - GM命令响应 */
  G2C_GM_COMMAND_RESPONSE = 301,
  UNRECOGNIZED = -1,
}

export function messageIDFromJSON(object: any): MessageID {
  switch (object) {
    case 0:
    case "NONE":
      return MessageID.NONE;
    case 1:
    case "C2L_LOGIN_REQUEST":
      return MessageID.C2L_LOGIN_REQUEST;
    case 2:
    case "L2C_LOGIN_RESPONSE":
      return MessageID.L2C_LOGIN_RESPONSE;
    case 3:
    case "C2G_HEARTBEAT_REQUEST":
      return MessageID.C2G_HEARTBEAT_REQUEST;
    case 4:
    case "G2C_HEARTBEAT_RESPONSE":
      return MessageID.G2C_HEARTBEAT_RESPONSE;
    case 5:
    case "C2G_USER_INFO_REQUEST":
      return MessageID.C2G_USER_INFO_REQUEST;
    case 6:
    case "G2C_USER_INFO_RESPONSE":
      return MessageID.G2C_USER_INFO_RESPONSE;
    case 100:
    case "C2G_USER_CARDS_REQUEST":
      return MessageID.C2G_USER_CARDS_REQUEST;
    case 101:
    case "G2C_USER_CARDS_RESPONSE":
      return MessageID.G2C_USER_CARDS_RESPONSE;
    case 200:
    case "C2G_BAG_INFO_REQUEST":
      return MessageID.C2G_BAG_INFO_REQUEST;
    case 201:
    case "G2C_BAG_INFO_RESPONSE":
      return MessageID.G2C_BAG_INFO_RESPONSE;
    case 202:
    case "C2G_USE_ITEM_REQUEST":
      return MessageID.C2G_USE_ITEM_REQUEST;
    case 203:
    case "G2C_USE_ITEM_RESPONSE":
      return MessageID.G2C_USE_ITEM_RESPONSE;
    case 204:
    case "C2G_EXPAND_BAG_REQUEST":
      return MessageID.C2G_EXPAND_BAG_REQUEST;
    case 205:
    case "G2C_EXPAND_BAG_RESPONSE":
      return MessageID.G2C_EXPAND_BAG_RESPONSE;
    case 206:
    case "C2G_SORT_BAG_REQUEST":
      return MessageID.C2G_SORT_BAG_REQUEST;
    case 207:
    case "G2C_SORT_BAG_RESPONSE":
      return MessageID.G2C_SORT_BAG_RESPONSE;
    case 208:
    case "C2G_MOVE_ITEM_REQUEST":
      return MessageID.C2G_MOVE_ITEM_REQUEST;
    case 209:
    case "G2C_MOVE_ITEM_RESPONSE":
      return MessageID.G2C_MOVE_ITEM_RESPONSE;
    case 210:
    case "C2G_COMPOSE_ITEM_REQUEST":
      return MessageID.C2G_COMPOSE_ITEM_REQUEST;
    case 211:
    case "G2C_COMPOSE_ITEM_RESPONSE":
      return MessageID.G2C_COMPOSE_ITEM_RESPONSE;
    case 212:
    case "C2G_DECOMPOSE_ITEM_REQUEST":
      return MessageID.C2G_DECOMPOSE_ITEM_REQUEST;
    case 213:
    case "G2C_DECOMPOSE_ITEM_RESPONSE":
      return MessageID.G2C_DECOMPOSE_ITEM_RESPONSE;
    case 300:
    case "C2G_GM_COMMAND_REQUEST":
      return MessageID.C2G_GM_COMMAND_REQUEST;
    case 301:
    case "G2C_GM_COMMAND_RESPONSE":
      return MessageID.G2C_GM_COMMAND_RESPONSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageID.UNRECOGNIZED;
  }
}

export function messageIDToJSON(object: MessageID): string {
  switch (object) {
    case MessageID.NONE:
      return "NONE";
    case MessageID.C2L_LOGIN_REQUEST:
      return "C2L_LOGIN_REQUEST";
    case MessageID.L2C_LOGIN_RESPONSE:
      return "L2C_LOGIN_RESPONSE";
    case MessageID.C2G_HEARTBEAT_REQUEST:
      return "C2G_HEARTBEAT_REQUEST";
    case MessageID.G2C_HEARTBEAT_RESPONSE:
      return "G2C_HEARTBEAT_RESPONSE";
    case MessageID.C2G_USER_INFO_REQUEST:
      return "C2G_USER_INFO_REQUEST";
    case MessageID.G2C_USER_INFO_RESPONSE:
      return "G2C_USER_INFO_RESPONSE";
    case MessageID.C2G_USER_CARDS_REQUEST:
      return "C2G_USER_CARDS_REQUEST";
    case MessageID.G2C_USER_CARDS_RESPONSE:
      return "G2C_USER_CARDS_RESPONSE";
    case MessageID.C2G_BAG_INFO_REQUEST:
      return "C2G_BAG_INFO_REQUEST";
    case MessageID.G2C_BAG_INFO_RESPONSE:
      return "G2C_BAG_INFO_RESPONSE";
    case MessageID.C2G_USE_ITEM_REQUEST:
      return "C2G_USE_ITEM_REQUEST";
    case MessageID.G2C_USE_ITEM_RESPONSE:
      return "G2C_USE_ITEM_RESPONSE";
    case MessageID.C2G_EXPAND_BAG_REQUEST:
      return "C2G_EXPAND_BAG_REQUEST";
    case MessageID.G2C_EXPAND_BAG_RESPONSE:
      return "G2C_EXPAND_BAG_RESPONSE";
    case MessageID.C2G_SORT_BAG_REQUEST:
      return "C2G_SORT_BAG_REQUEST";
    case MessageID.G2C_SORT_BAG_RESPONSE:
      return "G2C_SORT_BAG_RESPONSE";
    case MessageID.C2G_MOVE_ITEM_REQUEST:
      return "C2G_MOVE_ITEM_REQUEST";
    case MessageID.G2C_MOVE_ITEM_RESPONSE:
      return "G2C_MOVE_ITEM_RESPONSE";
    case MessageID.C2G_COMPOSE_ITEM_REQUEST:
      return "C2G_COMPOSE_ITEM_REQUEST";
    case MessageID.G2C_COMPOSE_ITEM_RESPONSE:
      return "G2C_COMPOSE_ITEM_RESPONSE";
    case MessageID.C2G_DECOMPOSE_ITEM_REQUEST:
      return "C2G_DECOMPOSE_ITEM_REQUEST";
    case MessageID.G2C_DECOMPOSE_ITEM_RESPONSE:
      return "G2C_DECOMPOSE_ITEM_RESPONSE";
    case MessageID.C2G_GM_COMMAND_REQUEST:
      return "C2G_GM_COMMAND_REQUEST";
    case MessageID.G2C_GM_COMMAND_RESPONSE:
      return "G2C_GM_COMMAND_RESPONSE";
    case MessageID.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 会话信息 */
export interface Session {
  /** 消息ID */
  messageId: number;
  /** 序列号 */
  sequence: number;
  /** 时间戳 */
  timestamp: number;
  /** 版本号 */
  version: string;
}

/** 基础请求 */
export interface BaseRequest {
  /** 会话信息 */
  session:
    | Session
    | undefined;
  /** 消息内容 */
  payload: Uint8Array;
}

/** 基础响应 */
export interface BaseResponse {
  /** 会话信息 */
  session:
    | Session
    | undefined;
  /** 错误码 */
  errorCode: number;
  /** 错误信息 */
  errorMsg: string;
  /** 消息负载 */
  payload: Uint8Array;
}

function createBaseSession(): Session {
  return { messageId: 0, sequence: 0, timestamp: 0, version: "" };
}

export const Session: MessageFns<Session> = {
  encode(message: Session, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.messageId !== 0) {
      writer.uint32(8).int32(message.messageId);
    }
    if (message.sequence !== 0) {
      writer.uint32(16).int32(message.sequence);
    }
    if (message.timestamp !== 0) {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.version !== "") {
      writer.uint32(34).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Session {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSession();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.messageId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sequence = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Session {
    return {
      messageId: isSet(object.messageId) ? globalThis.Number(object.messageId) : 0,
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      version: isSet(object.version) ? globalThis.String(object.version) : "",
    };
  },

  toJSON(message: Session): unknown {
    const obj: any = {};
    if (message.messageId !== 0) {
      obj.messageId = Math.round(message.messageId);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Session>, I>>(base?: I): Session {
    return Session.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Session>, I>>(object: I): Session {
    const message = createBaseSession();
    message.messageId = object.messageId ?? 0;
    message.sequence = object.sequence ?? 0;
    message.timestamp = object.timestamp ?? 0;
    message.version = object.version ?? "";
    return message;
  },
};

function createBaseBaseRequest(): BaseRequest {
  return { session: undefined, payload: new Uint8Array(0) };
}

export const BaseRequest: MessageFns<BaseRequest> = {
  encode(message: BaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseRequest {
    return {
      session: isSet(object.session) ? Session.fromJSON(object.session) : undefined,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: BaseRequest): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BaseRequest>, I>>(base?: I): BaseRequest {
    return BaseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BaseRequest>, I>>(object: I): BaseRequest {
    const message = createBaseBaseRequest();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseBaseResponse(): BaseResponse {
  return { session: undefined, errorCode: 0, errorMsg: "", payload: new Uint8Array(0) };
}

export const BaseResponse: MessageFns<BaseResponse> = {
  encode(message: BaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session !== undefined) {
      Session.encode(message.session, writer.uint32(10).fork()).join();
    }
    if (message.errorCode !== 0) {
      writer.uint32(16).int32(message.errorCode);
    }
    if (message.errorMsg !== "") {
      writer.uint32(26).string(message.errorMsg);
    }
    if (message.payload.length !== 0) {
      writer.uint32(34).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session = Session.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.errorCode = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMsg = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BaseResponse {
    return {
      session: isSet(object.session) ? Session.fromJSON(object.session) : undefined,
      errorCode: isSet(object.errorCode) ? globalThis.Number(object.errorCode) : 0,
      errorMsg: isSet(object.errorMsg) ? globalThis.String(object.errorMsg) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: BaseResponse): unknown {
    const obj: any = {};
    if (message.session !== undefined) {
      obj.session = Session.toJSON(message.session);
    }
    if (message.errorCode !== 0) {
      obj.errorCode = Math.round(message.errorCode);
    }
    if (message.errorMsg !== "") {
      obj.errorMsg = message.errorMsg;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BaseResponse>, I>>(base?: I): BaseResponse {
    return BaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BaseResponse>, I>>(object: I): BaseResponse {
    const message = createBaseBaseResponse();
    message.session = (object.session !== undefined && object.session !== null)
      ? Session.fromPartial(object.session)
      : undefined;
    message.errorCode = object.errorCode ?? 0;
    message.errorMsg = object.errorMsg ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
