// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: command/command.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BagInfo, CardInfo, ItemInfo, UserInfo } from "../common/entity";
import { BagType, bagTypeFromJSON, bagTypeToJSON } from "../common/enum";

export const protobufPackage = "command";

/** 登录请求 {{Req:1}} */
export interface C2LLoginRequest {
  /** 账号 */
  account: string;
  /** 密码 */
  password: string;
  /** 设备ID */
  deviceId: string;
  /** 平台标识 */
  platform: string;
  /** 客户端版本 */
  version: string;
}

/** 登录响应 {{Res:2}} */
export interface L2CLoginResponse {
  /** JWT令牌 */
  token: string;
  /** WebSocket地址 */
  wsAddr: string;
  /** WebSocket端口 */
  wsPort: number;
}

/** 心跳请求 {{Req:3}} */
export interface C2GHeartbeatRequest {
  /** 时间戳 */
  timestamp: number;
  /** JWT令牌,用于身份验证 */
  token: string;
}

/** 心跳响应 {{Res:4}} */
export interface G2CHeartbeatResponse {
  /** 服务器时间戳 */
  timestamp: number;
}

/** 获取用户信息请求 {{Req:5}} */
export interface C2GUserInfoRequest {
  /** JWT令牌 */
  token: string;
}

/** 获取用户信息响应 {{Res:6}} */
export interface G2CUserInfoResponse {
  /** 用户信息 */
  user:
    | UserInfo
    | undefined;
  /** 是否是新创建的用户 */
  isNew: boolean;
}

/** 获取用户卡牌请求 {{Req:100}} */
export interface C2GUserCardsRequest {
  /** JWT令牌 */
  token: string;
}

/** 获取用户卡牌响应 {{Res:101}} */
export interface G2CUserCardsResponse {
  /** 卡牌列表 */
  cards: CardInfo[];
}

/** 获取背包信息请求 {{Req:200}} */
export interface C2GBagInfoRequest {
  token: string;
}

/** 背包信息响应 {{Res:201}} */
export interface G2CBagInfoResponse {
  /** 背包信息列表 */
  bags: BagInfo[];
}

/** 使用物品请求 {{Req:202}} */
export interface C2GUseItemRequest {
  /** 用户令牌 */
  token: string;
  /** 物品ID */
  itemId: number;
  /** 使用数量 */
  count: number;
}

/** 使用物品响应 {{Res:203}} */
export interface G2CUseItemResponse {
  /** 变化的物品列表 */
  items: ItemInfo[];
}

/** 扩展背包请求 {{Req:204}} */
export interface C2GExpandBagRequest {
  token: string;
  /** 使用枚举类型 */
  bagType: BagType;
  addSize: number;
}

/** 扩展背包响应 {{Res:205}} */
export interface G2CExpandBagResponse {
  /** 背包信息 */
  bag: BagInfo | undefined;
}

/** 整理背包请求 {{Req:206}} */
export interface C2GSortBagRequest {
  /** JWT令牌 */
  token: string;
  /** 背包类型 */
  bagType: BagType;
  /** 整理规则(1:类型 2:品质 3:等级) */
  sortRule: number;
}

/** 整理背包响应 {{Res:207}} */
export interface G2CSortBagResponse {
  /** 整理后的物品列表 */
  items: ItemInfo[];
}

/** 移动物品请求 {{Req:208}} */
export interface C2GMoveItemRequest {
  token: string;
  /** 源背包类型 */
  srcBagType: number;
  /** 源格子位置 */
  srcSlot: number;
  /** 目标背包类型 */
  dstBagType: number;
  /** 目标格子位置 */
  dstSlot: number;
  /** 可选的移动数量 */
  count: number;
}

/** 移动物品响应 {{Res:209}} */
export interface G2CMoveItemResponse {
  /** 所有变化的物品 */
  changedItems: ItemInfo[];
}

/** 物品合成请求 {{Req:210}} */
export interface C2GComposeItemRequest {
  /** JWT令牌 */
  token: string;
  /** 目标物品ID */
  targetId: number;
  /** 材料所在格子 */
  materialSlots: number[];
}

/** 物品合成响应 {{Res:211}} */
export interface G2CComposeItemResponse {
  /** 是否成功 */
  success: boolean;
  /** 合成的新物品 */
  newItem:
    | ItemInfo
    | undefined;
  /** 剩余材料 */
  remainItems: ItemInfo[];
}

/** 物品分解请求 {{Req:212}} */
export interface C2GDecomposeItemRequest {
  /** JWT令牌 */
  token: string;
  /** 要分解的物品格子 */
  itemSlots: number[];
}

/** 物品分解响应 {{Res:213}} */
export interface G2CDecomposeItemResponse {
  /** 分解获得的物品 */
  resultItems: ItemInfo[];
}

/** GM指令请求 {{Req:300}} */
export interface C2GGmCommandRequest {
  /** 令牌 */
  token: string;
  /** GM指令 */
  command: string;
  /** 参数列表 */
  params: string[];
}

/** GM指令响应 {{Res:301}} */
export interface G2CGmCommandResponse {
  /** 结果 */
  result: string;
  /** 消息 */
  message: string;
}

function createBaseC2LLoginRequest(): C2LLoginRequest {
  return { account: "", password: "", deviceId: "", platform: "", version: "" };
}

export const C2LLoginRequest: MessageFns<C2LLoginRequest> = {
  encode(message: C2LLoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.deviceId !== "") {
      writer.uint32(26).string(message.deviceId);
    }
    if (message.platform !== "") {
      writer.uint32(34).string(message.platform);
    }
    if (message.version !== "") {
      writer.uint32(42).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2LLoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2LLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2LLoginRequest {
    return {
      account: isSet(object.account) ? globalThis.String(object.account) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      deviceId: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
    };
  },

  toJSON(message: C2LLoginRequest): unknown {
    const obj: any = {};
    if (message.account !== "") {
      obj.account = message.account;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2LLoginRequest>, I>>(base?: I): C2LLoginRequest {
    return C2LLoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2LLoginRequest>, I>>(object: I): C2LLoginRequest {
    const message = createBaseC2LLoginRequest();
    message.account = object.account ?? "";
    message.password = object.password ?? "";
    message.deviceId = object.deviceId ?? "";
    message.platform = object.platform ?? "";
    message.version = object.version ?? "";
    return message;
  },
};

function createBaseL2CLoginResponse(): L2CLoginResponse {
  return { token: "", wsAddr: "", wsPort: 0 };
}

export const L2CLoginResponse: MessageFns<L2CLoginResponse> = {
  encode(message: L2CLoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.wsAddr !== "") {
      writer.uint32(18).string(message.wsAddr);
    }
    if (message.wsPort !== 0) {
      writer.uint32(24).int32(message.wsPort);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): L2CLoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseL2CLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.wsAddr = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.wsPort = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): L2CLoginResponse {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      wsAddr: isSet(object.wsAddr) ? globalThis.String(object.wsAddr) : "",
      wsPort: isSet(object.wsPort) ? globalThis.Number(object.wsPort) : 0,
    };
  },

  toJSON(message: L2CLoginResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.wsAddr !== "") {
      obj.wsAddr = message.wsAddr;
    }
    if (message.wsPort !== 0) {
      obj.wsPort = Math.round(message.wsPort);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<L2CLoginResponse>, I>>(base?: I): L2CLoginResponse {
    return L2CLoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<L2CLoginResponse>, I>>(object: I): L2CLoginResponse {
    const message = createBaseL2CLoginResponse();
    message.token = object.token ?? "";
    message.wsAddr = object.wsAddr ?? "";
    message.wsPort = object.wsPort ?? 0;
    return message;
  },
};

function createBaseC2GHeartbeatRequest(): C2GHeartbeatRequest {
  return { timestamp: 0, token: "" };
}

export const C2GHeartbeatRequest: MessageFns<C2GHeartbeatRequest> = {
  encode(message: C2GHeartbeatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GHeartbeatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GHeartbeatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GHeartbeatRequest {
    return {
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: C2GHeartbeatRequest): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GHeartbeatRequest>, I>>(base?: I): C2GHeartbeatRequest {
    return C2GHeartbeatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GHeartbeatRequest>, I>>(object: I): C2GHeartbeatRequest {
    const message = createBaseC2GHeartbeatRequest();
    message.timestamp = object.timestamp ?? 0;
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseG2CHeartbeatResponse(): G2CHeartbeatResponse {
  return { timestamp: 0 };
}

export const G2CHeartbeatResponse: MessageFns<G2CHeartbeatResponse> = {
  encode(message: G2CHeartbeatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.timestamp !== 0) {
      writer.uint32(8).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CHeartbeatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CHeartbeatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CHeartbeatResponse {
    return { timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0 };
  },

  toJSON(message: G2CHeartbeatResponse): unknown {
    const obj: any = {};
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CHeartbeatResponse>, I>>(base?: I): G2CHeartbeatResponse {
    return G2CHeartbeatResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CHeartbeatResponse>, I>>(object: I): G2CHeartbeatResponse {
    const message = createBaseG2CHeartbeatResponse();
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseC2GUserInfoRequest(): C2GUserInfoRequest {
  return { token: "" };
}

export const C2GUserInfoRequest: MessageFns<C2GUserInfoRequest> = {
  encode(message: C2GUserInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GUserInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GUserInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GUserInfoRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: C2GUserInfoRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GUserInfoRequest>, I>>(base?: I): C2GUserInfoRequest {
    return C2GUserInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GUserInfoRequest>, I>>(object: I): C2GUserInfoRequest {
    const message = createBaseC2GUserInfoRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseG2CUserInfoResponse(): G2CUserInfoResponse {
  return { user: undefined, isNew: false };
}

export const G2CUserInfoResponse: MessageFns<G2CUserInfoResponse> = {
  encode(message: G2CUserInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      UserInfo.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.isNew !== false) {
      writer.uint32(16).bool(message.isNew);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CUserInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CUserInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = UserInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isNew = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CUserInfoResponse {
    return {
      user: isSet(object.user) ? UserInfo.fromJSON(object.user) : undefined,
      isNew: isSet(object.isNew) ? globalThis.Boolean(object.isNew) : false,
    };
  },

  toJSON(message: G2CUserInfoResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = UserInfo.toJSON(message.user);
    }
    if (message.isNew !== false) {
      obj.isNew = message.isNew;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CUserInfoResponse>, I>>(base?: I): G2CUserInfoResponse {
    return G2CUserInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CUserInfoResponse>, I>>(object: I): G2CUserInfoResponse {
    const message = createBaseG2CUserInfoResponse();
    message.user = (object.user !== undefined && object.user !== null) ? UserInfo.fromPartial(object.user) : undefined;
    message.isNew = object.isNew ?? false;
    return message;
  },
};

function createBaseC2GUserCardsRequest(): C2GUserCardsRequest {
  return { token: "" };
}

export const C2GUserCardsRequest: MessageFns<C2GUserCardsRequest> = {
  encode(message: C2GUserCardsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GUserCardsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GUserCardsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GUserCardsRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: C2GUserCardsRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GUserCardsRequest>, I>>(base?: I): C2GUserCardsRequest {
    return C2GUserCardsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GUserCardsRequest>, I>>(object: I): C2GUserCardsRequest {
    const message = createBaseC2GUserCardsRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseG2CUserCardsResponse(): G2CUserCardsResponse {
  return { cards: [] };
}

export const G2CUserCardsResponse: MessageFns<G2CUserCardsResponse> = {
  encode(message: G2CUserCardsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.cards) {
      CardInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CUserCardsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CUserCardsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cards.push(CardInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CUserCardsResponse {
    return { cards: globalThis.Array.isArray(object?.cards) ? object.cards.map((e: any) => CardInfo.fromJSON(e)) : [] };
  },

  toJSON(message: G2CUserCardsResponse): unknown {
    const obj: any = {};
    if (message.cards?.length) {
      obj.cards = message.cards.map((e) => CardInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CUserCardsResponse>, I>>(base?: I): G2CUserCardsResponse {
    return G2CUserCardsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CUserCardsResponse>, I>>(object: I): G2CUserCardsResponse {
    const message = createBaseG2CUserCardsResponse();
    message.cards = object.cards?.map((e) => CardInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GBagInfoRequest(): C2GBagInfoRequest {
  return { token: "" };
}

export const C2GBagInfoRequest: MessageFns<C2GBagInfoRequest> = {
  encode(message: C2GBagInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GBagInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GBagInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GBagInfoRequest {
    return { token: isSet(object.token) ? globalThis.String(object.token) : "" };
  },

  toJSON(message: C2GBagInfoRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GBagInfoRequest>, I>>(base?: I): C2GBagInfoRequest {
    return C2GBagInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GBagInfoRequest>, I>>(object: I): C2GBagInfoRequest {
    const message = createBaseC2GBagInfoRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseG2CBagInfoResponse(): G2CBagInfoResponse {
  return { bags: [] };
}

export const G2CBagInfoResponse: MessageFns<G2CBagInfoResponse> = {
  encode(message: G2CBagInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.bags) {
      BagInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CBagInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CBagInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bags.push(BagInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CBagInfoResponse {
    return { bags: globalThis.Array.isArray(object?.bags) ? object.bags.map((e: any) => BagInfo.fromJSON(e)) : [] };
  },

  toJSON(message: G2CBagInfoResponse): unknown {
    const obj: any = {};
    if (message.bags?.length) {
      obj.bags = message.bags.map((e) => BagInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CBagInfoResponse>, I>>(base?: I): G2CBagInfoResponse {
    return G2CBagInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CBagInfoResponse>, I>>(object: I): G2CBagInfoResponse {
    const message = createBaseG2CBagInfoResponse();
    message.bags = object.bags?.map((e) => BagInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GUseItemRequest(): C2GUseItemRequest {
  return { token: "", itemId: 0, count: 0 };
}

export const C2GUseItemRequest: MessageFns<C2GUseItemRequest> = {
  encode(message: C2GUseItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.itemId !== 0) {
      writer.uint32(16).int32(message.itemId);
    }
    if (message.count !== 0) {
      writer.uint32(24).int32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GUseItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GUseItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.itemId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GUseItemRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      itemId: isSet(object.itemId) ? globalThis.Number(object.itemId) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: C2GUseItemRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GUseItemRequest>, I>>(base?: I): C2GUseItemRequest {
    return C2GUseItemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GUseItemRequest>, I>>(object: I): C2GUseItemRequest {
    const message = createBaseC2GUseItemRequest();
    message.token = object.token ?? "";
    message.itemId = object.itemId ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseG2CUseItemResponse(): G2CUseItemResponse {
  return { items: [] };
}

export const G2CUseItemResponse: MessageFns<G2CUseItemResponse> = {
  encode(message: G2CUseItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CUseItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CUseItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CUseItemResponse {
    return { items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => ItemInfo.fromJSON(e)) : [] };
  },

  toJSON(message: G2CUseItemResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CUseItemResponse>, I>>(base?: I): G2CUseItemResponse {
    return G2CUseItemResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CUseItemResponse>, I>>(object: I): G2CUseItemResponse {
    const message = createBaseG2CUseItemResponse();
    message.items = object.items?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GExpandBagRequest(): C2GExpandBagRequest {
  return { token: "", bagType: 0, addSize: 0 };
}

export const C2GExpandBagRequest: MessageFns<C2GExpandBagRequest> = {
  encode(message: C2GExpandBagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.bagType !== 0) {
      writer.uint32(16).int32(message.bagType);
    }
    if (message.addSize !== 0) {
      writer.uint32(24).int32(message.addSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GExpandBagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GExpandBagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bagType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.addSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GExpandBagRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      bagType: isSet(object.bagType) ? bagTypeFromJSON(object.bagType) : 0,
      addSize: isSet(object.addSize) ? globalThis.Number(object.addSize) : 0,
    };
  },

  toJSON(message: C2GExpandBagRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.bagType !== 0) {
      obj.bagType = bagTypeToJSON(message.bagType);
    }
    if (message.addSize !== 0) {
      obj.addSize = Math.round(message.addSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GExpandBagRequest>, I>>(base?: I): C2GExpandBagRequest {
    return C2GExpandBagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GExpandBagRequest>, I>>(object: I): C2GExpandBagRequest {
    const message = createBaseC2GExpandBagRequest();
    message.token = object.token ?? "";
    message.bagType = object.bagType ?? 0;
    message.addSize = object.addSize ?? 0;
    return message;
  },
};

function createBaseG2CExpandBagResponse(): G2CExpandBagResponse {
  return { bag: undefined };
}

export const G2CExpandBagResponse: MessageFns<G2CExpandBagResponse> = {
  encode(message: G2CExpandBagResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bag !== undefined) {
      BagInfo.encode(message.bag, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CExpandBagResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CExpandBagResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bag = BagInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CExpandBagResponse {
    return { bag: isSet(object.bag) ? BagInfo.fromJSON(object.bag) : undefined };
  },

  toJSON(message: G2CExpandBagResponse): unknown {
    const obj: any = {};
    if (message.bag !== undefined) {
      obj.bag = BagInfo.toJSON(message.bag);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CExpandBagResponse>, I>>(base?: I): G2CExpandBagResponse {
    return G2CExpandBagResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CExpandBagResponse>, I>>(object: I): G2CExpandBagResponse {
    const message = createBaseG2CExpandBagResponse();
    message.bag = (object.bag !== undefined && object.bag !== null) ? BagInfo.fromPartial(object.bag) : undefined;
    return message;
  },
};

function createBaseC2GSortBagRequest(): C2GSortBagRequest {
  return { token: "", bagType: 0, sortRule: 0 };
}

export const C2GSortBagRequest: MessageFns<C2GSortBagRequest> = {
  encode(message: C2GSortBagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.bagType !== 0) {
      writer.uint32(16).int32(message.bagType);
    }
    if (message.sortRule !== 0) {
      writer.uint32(24).int32(message.sortRule);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GSortBagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GSortBagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bagType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sortRule = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GSortBagRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      bagType: isSet(object.bagType) ? bagTypeFromJSON(object.bagType) : 0,
      sortRule: isSet(object.sortRule) ? globalThis.Number(object.sortRule) : 0,
    };
  },

  toJSON(message: C2GSortBagRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.bagType !== 0) {
      obj.bagType = bagTypeToJSON(message.bagType);
    }
    if (message.sortRule !== 0) {
      obj.sortRule = Math.round(message.sortRule);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GSortBagRequest>, I>>(base?: I): C2GSortBagRequest {
    return C2GSortBagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GSortBagRequest>, I>>(object: I): C2GSortBagRequest {
    const message = createBaseC2GSortBagRequest();
    message.token = object.token ?? "";
    message.bagType = object.bagType ?? 0;
    message.sortRule = object.sortRule ?? 0;
    return message;
  },
};

function createBaseG2CSortBagResponse(): G2CSortBagResponse {
  return { items: [] };
}

export const G2CSortBagResponse: MessageFns<G2CSortBagResponse> = {
  encode(message: G2CSortBagResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CSortBagResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CSortBagResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CSortBagResponse {
    return { items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => ItemInfo.fromJSON(e)) : [] };
  },

  toJSON(message: G2CSortBagResponse): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CSortBagResponse>, I>>(base?: I): G2CSortBagResponse {
    return G2CSortBagResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CSortBagResponse>, I>>(object: I): G2CSortBagResponse {
    const message = createBaseG2CSortBagResponse();
    message.items = object.items?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GMoveItemRequest(): C2GMoveItemRequest {
  return { token: "", srcBagType: 0, srcSlot: 0, dstBagType: 0, dstSlot: 0, count: 0 };
}

export const C2GMoveItemRequest: MessageFns<C2GMoveItemRequest> = {
  encode(message: C2GMoveItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.srcBagType !== 0) {
      writer.uint32(16).int32(message.srcBagType);
    }
    if (message.srcSlot !== 0) {
      writer.uint32(24).int32(message.srcSlot);
    }
    if (message.dstBagType !== 0) {
      writer.uint32(32).int32(message.dstBagType);
    }
    if (message.dstSlot !== 0) {
      writer.uint32(40).int32(message.dstSlot);
    }
    if (message.count !== 0) {
      writer.uint32(48).int32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GMoveItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GMoveItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.srcBagType = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.srcSlot = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dstBagType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dstSlot = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GMoveItemRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      srcBagType: isSet(object.srcBagType) ? globalThis.Number(object.srcBagType) : 0,
      srcSlot: isSet(object.srcSlot) ? globalThis.Number(object.srcSlot) : 0,
      dstBagType: isSet(object.dstBagType) ? globalThis.Number(object.dstBagType) : 0,
      dstSlot: isSet(object.dstSlot) ? globalThis.Number(object.dstSlot) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: C2GMoveItemRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.srcBagType !== 0) {
      obj.srcBagType = Math.round(message.srcBagType);
    }
    if (message.srcSlot !== 0) {
      obj.srcSlot = Math.round(message.srcSlot);
    }
    if (message.dstBagType !== 0) {
      obj.dstBagType = Math.round(message.dstBagType);
    }
    if (message.dstSlot !== 0) {
      obj.dstSlot = Math.round(message.dstSlot);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GMoveItemRequest>, I>>(base?: I): C2GMoveItemRequest {
    return C2GMoveItemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GMoveItemRequest>, I>>(object: I): C2GMoveItemRequest {
    const message = createBaseC2GMoveItemRequest();
    message.token = object.token ?? "";
    message.srcBagType = object.srcBagType ?? 0;
    message.srcSlot = object.srcSlot ?? 0;
    message.dstBagType = object.dstBagType ?? 0;
    message.dstSlot = object.dstSlot ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseG2CMoveItemResponse(): G2CMoveItemResponse {
  return { changedItems: [] };
}

export const G2CMoveItemResponse: MessageFns<G2CMoveItemResponse> = {
  encode(message: G2CMoveItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.changedItems) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CMoveItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CMoveItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.changedItems.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CMoveItemResponse {
    return {
      changedItems: globalThis.Array.isArray(object?.changedItems)
        ? object.changedItems.map((e: any) => ItemInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: G2CMoveItemResponse): unknown {
    const obj: any = {};
    if (message.changedItems?.length) {
      obj.changedItems = message.changedItems.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CMoveItemResponse>, I>>(base?: I): G2CMoveItemResponse {
    return G2CMoveItemResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CMoveItemResponse>, I>>(object: I): G2CMoveItemResponse {
    const message = createBaseG2CMoveItemResponse();
    message.changedItems = object.changedItems?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GComposeItemRequest(): C2GComposeItemRequest {
  return { token: "", targetId: 0, materialSlots: [] };
}

export const C2GComposeItemRequest: MessageFns<C2GComposeItemRequest> = {
  encode(message: C2GComposeItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.targetId !== 0) {
      writer.uint32(16).int32(message.targetId);
    }
    writer.uint32(26).fork();
    for (const v of message.materialSlots) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GComposeItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GComposeItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.targetId = reader.int32();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.materialSlots.push(reader.int32());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.materialSlots.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GComposeItemRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      targetId: isSet(object.targetId) ? globalThis.Number(object.targetId) : 0,
      materialSlots: globalThis.Array.isArray(object?.materialSlots)
        ? object.materialSlots.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: C2GComposeItemRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.targetId !== 0) {
      obj.targetId = Math.round(message.targetId);
    }
    if (message.materialSlots?.length) {
      obj.materialSlots = message.materialSlots.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GComposeItemRequest>, I>>(base?: I): C2GComposeItemRequest {
    return C2GComposeItemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GComposeItemRequest>, I>>(object: I): C2GComposeItemRequest {
    const message = createBaseC2GComposeItemRequest();
    message.token = object.token ?? "";
    message.targetId = object.targetId ?? 0;
    message.materialSlots = object.materialSlots?.map((e) => e) || [];
    return message;
  },
};

function createBaseG2CComposeItemResponse(): G2CComposeItemResponse {
  return { success: false, newItem: undefined, remainItems: [] };
}

export const G2CComposeItemResponse: MessageFns<G2CComposeItemResponse> = {
  encode(message: G2CComposeItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.newItem !== undefined) {
      ItemInfo.encode(message.newItem, writer.uint32(18).fork()).join();
    }
    for (const v of message.remainItems) {
      ItemInfo.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CComposeItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CComposeItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newItem = ItemInfo.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.remainItems.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CComposeItemResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      newItem: isSet(object.newItem) ? ItemInfo.fromJSON(object.newItem) : undefined,
      remainItems: globalThis.Array.isArray(object?.remainItems)
        ? object.remainItems.map((e: any) => ItemInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: G2CComposeItemResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.newItem !== undefined) {
      obj.newItem = ItemInfo.toJSON(message.newItem);
    }
    if (message.remainItems?.length) {
      obj.remainItems = message.remainItems.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CComposeItemResponse>, I>>(base?: I): G2CComposeItemResponse {
    return G2CComposeItemResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CComposeItemResponse>, I>>(object: I): G2CComposeItemResponse {
    const message = createBaseG2CComposeItemResponse();
    message.success = object.success ?? false;
    message.newItem = (object.newItem !== undefined && object.newItem !== null)
      ? ItemInfo.fromPartial(object.newItem)
      : undefined;
    message.remainItems = object.remainItems?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GDecomposeItemRequest(): C2GDecomposeItemRequest {
  return { token: "", itemSlots: [] };
}

export const C2GDecomposeItemRequest: MessageFns<C2GDecomposeItemRequest> = {
  encode(message: C2GDecomposeItemRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    writer.uint32(18).fork();
    for (const v of message.itemSlots) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GDecomposeItemRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GDecomposeItemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.itemSlots.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.itemSlots.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GDecomposeItemRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      itemSlots: globalThis.Array.isArray(object?.itemSlots)
        ? object.itemSlots.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: C2GDecomposeItemRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.itemSlots?.length) {
      obj.itemSlots = message.itemSlots.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GDecomposeItemRequest>, I>>(base?: I): C2GDecomposeItemRequest {
    return C2GDecomposeItemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GDecomposeItemRequest>, I>>(object: I): C2GDecomposeItemRequest {
    const message = createBaseC2GDecomposeItemRequest();
    message.token = object.token ?? "";
    message.itemSlots = object.itemSlots?.map((e) => e) || [];
    return message;
  },
};

function createBaseG2CDecomposeItemResponse(): G2CDecomposeItemResponse {
  return { resultItems: [] };
}

export const G2CDecomposeItemResponse: MessageFns<G2CDecomposeItemResponse> = {
  encode(message: G2CDecomposeItemResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.resultItems) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CDecomposeItemResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CDecomposeItemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resultItems.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CDecomposeItemResponse {
    return {
      resultItems: globalThis.Array.isArray(object?.resultItems)
        ? object.resultItems.map((e: any) => ItemInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: G2CDecomposeItemResponse): unknown {
    const obj: any = {};
    if (message.resultItems?.length) {
      obj.resultItems = message.resultItems.map((e) => ItemInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CDecomposeItemResponse>, I>>(base?: I): G2CDecomposeItemResponse {
    return G2CDecomposeItemResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CDecomposeItemResponse>, I>>(object: I): G2CDecomposeItemResponse {
    const message = createBaseG2CDecomposeItemResponse();
    message.resultItems = object.resultItems?.map((e) => ItemInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseC2GGmCommandRequest(): C2GGmCommandRequest {
  return { token: "", command: "", params: [] };
}

export const C2GGmCommandRequest: MessageFns<C2GGmCommandRequest> = {
  encode(message: C2GGmCommandRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.command !== "") {
      writer.uint32(18).string(message.command);
    }
    for (const v of message.params) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): C2GGmCommandRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseC2GGmCommandRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.command = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.params.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): C2GGmCommandRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      command: isSet(object.command) ? globalThis.String(object.command) : "",
      params: globalThis.Array.isArray(object?.params) ? object.params.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: C2GGmCommandRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.command !== "") {
      obj.command = message.command;
    }
    if (message.params?.length) {
      obj.params = message.params;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<C2GGmCommandRequest>, I>>(base?: I): C2GGmCommandRequest {
    return C2GGmCommandRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<C2GGmCommandRequest>, I>>(object: I): C2GGmCommandRequest {
    const message = createBaseC2GGmCommandRequest();
    message.token = object.token ?? "";
    message.command = object.command ?? "";
    message.params = object.params?.map((e) => e) || [];
    return message;
  },
};

function createBaseG2CGmCommandResponse(): G2CGmCommandResponse {
  return { result: "", message: "" };
}

export const G2CGmCommandResponse: MessageFns<G2CGmCommandResponse> = {
  encode(message: G2CGmCommandResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== "") {
      writer.uint32(10).string(message.result);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): G2CGmCommandResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseG2CGmCommandResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.result = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): G2CGmCommandResponse {
    return {
      result: isSet(object.result) ? globalThis.String(object.result) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: G2CGmCommandResponse): unknown {
    const obj: any = {};
    if (message.result !== "") {
      obj.result = message.result;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<G2CGmCommandResponse>, I>>(base?: I): G2CGmCommandResponse {
    return G2CGmCommandResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<G2CGmCommandResponse>, I>>(object: I): G2CGmCommandResponse {
    const message = createBaseG2CGmCommandResponse();
    message.result = object.result ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
