// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.5.0
// source: command/command.proto

/* eslint-disable */
import {
  BagInfo,
  CardInfo,
  ItemInfo,
  MailInfo,
  PartnerInfo,
  PropertyChange,
  ResourceInfo,
  UserInfo,
} from "../common/entity";
import { BagType } from "../common/enum";

export const protobufPackage = "command";

/** 登录请求 {{Req:1}} */
export interface C2LLoginRequest {
  $type: "command.C2LLoginRequest";
  /** 账号 */
  account: string;
  /** 密码 */
  password: string;
  /** 设备ID */
  deviceId: string;
  /** 平台标识 */
  platform: string;
  /** 客户端版本 */
  version: string;
}

/** 登录响应 {{Res:2}} */
export interface L2CLoginResponse {
  $type: "command.L2CLoginResponse";
  /** JWT令牌 */
  token: string;
  /** WebSocket地址 */
  wsAddr: string;
  /** WebSocket端口 */
  wsPort: number;
}

/** 心跳请求 {{Req:3}} */
export interface C2GHeartbeatRequest {
  $type: "command.C2GHeartbeatRequest";
  /** 时间戳 */
  timestamp: bigint;
  /** JWT令牌,用于身份验证 */
  token: string;
}

/** 心跳响应 {{Res:4}} */
export interface G2CHeartbeatResponse {
  $type: "command.G2CHeartbeatResponse";
  /** 服务器时间戳 */
  timestamp: bigint;
}

/** 获取用户信息请求 {{Req:5}} */
export interface C2GUserInfoRequest {
  $type: "command.C2GUserInfoRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取用户信息响应 {{Res:6}} */
export interface G2CUserInfoResponse {
  $type: "command.G2CUserInfoResponse";
  /** 用户信息 */
  user?:
    | UserInfo
    | undefined;
  /** 是否是新创建的用户 */
  isNew: boolean;
}

/** 游戏登录请求 {{Req:7}} */
export interface C2GLoginGameRequest {
  $type: "command.C2GLoginGameRequest";
  /** JWT令牌 */
  token: string;
}

/** 游戏登录响应 {{Res:8}} */
export interface G2CLoginGameResponse {
  $type: "command.G2CLoginGameResponse";
  /** 用户基本信息 */
  user?:
    | UserInfo
    | undefined;
  /** 是否是新创建的用户 */
  isNewUser: boolean;
  /** 背包信息 */
  bags: BagInfo[];
  /** 资源信息 */
  resources: ResourceInfo[];
  /** 服务器时间（毫秒） */
  serverTime: bigint;
}

/** 获取用户卡牌请求 {{Req:101}} */
export interface C2GUserCardsRequest {
  $type: "command.C2GUserCardsRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取用户卡牌响应 {{Res:102}} */
export interface G2CUserCardsResponse {
  $type: "command.G2CUserCardsResponse";
  /** 卡牌列表 */
  cards: CardInfo[];
}

/** 获取背包信息请求 {{Req:201}} */
export interface C2GBagInfoRequest {
  $type: "command.C2GBagInfoRequest";
  token: string;
}

/** 背包信息响应 {{Res:202}} */
export interface G2CBagInfoResponse {
  $type: "command.G2CBagInfoResponse";
  /** 背包信息列表 */
  bags: BagInfo[];
}

/** 使用物品请求 {{Req:203}} */
export interface C2GUseItemRequest {
  $type: "command.C2GUseItemRequest";
  /** 用户令牌 */
  token: string;
  /** 物品ID */
  itemId: number;
  /** 使用数量 */
  count: number;
}

/** 使用物品响应 {{Res:204=202}} */
export interface G2CUseItemResponse {
  $type: "command.G2CUseItemResponse";
  /** 变化的物品列表 */
  bags: BagInfo[];
}

/** 扩展背包请求 {{Req:205}} */
export interface C2GExpandBagRequest {
  $type: "command.C2GExpandBagRequest";
  token: string;
  /** 使用枚举类型 */
  bagType: BagType;
  addSize: number;
}

/** 扩展背包响应 {{Res:206}} */
export interface G2CExpandBagResponse {
  $type: "command.G2CExpandBagResponse";
  /** 背包信息 */
  bag?: BagInfo | undefined;
}

/** 整理背包请求 {{Req:207}} */
export interface C2GSortBagRequest {
  $type: "command.C2GSortBagRequest";
  /** JWT令牌 */
  token: string;
  /** 背包类型 */
  bagType: BagType;
  /** 整理规则(1:类型 2:品质 3:等级) */
  sortRule: number;
}

/** 整理背包响应 {{Res:208}} */
export interface G2CSortBagResponse {
  $type: "command.G2CSortBagResponse";
  /** 整理后的物品列表 */
  items: ItemInfo[];
}

/** 移动物品请求 {{Req:209}} */
export interface C2GMoveItemRequest {
  $type: "command.C2GMoveItemRequest";
  token: string;
  /** 源背包类型 */
  srcBagType: number;
  /** 源格子位置 */
  srcSlot: number;
  /** 目标背包类型 */
  dstBagType: number;
  /** 目标格子位置 */
  dstSlot: number;
  /** 可选的移动数量 */
  count: number;
}

/** 移动物品响应 {{Res:210}} */
export interface G2CMoveItemResponse {
  $type: "command.G2CMoveItemResponse";
  /** 所有变化的物品 */
  changedItems: ItemInfo[];
}

/** 物品合成请求 {{Req:211}} */
export interface C2GComposeItemRequest {
  $type: "command.C2GComposeItemRequest";
  /** JWT令牌 */
  token: string;
  /** 目标物品ID */
  targetId: number;
}

/** 物品合成响应 {{Res:212}} */
export interface G2CComposeItemResponse {
  $type: "command.G2CComposeItemResponse";
  /** 合成的新物品 */
  newItem?:
    | ItemInfo
    | undefined;
  /** 剩余材料 */
  remainItems: ItemInfo[];
}

/** 物品分解请求 {{Req:213}} */
export interface C2GDecomposeItemRequest {
  $type: "command.C2GDecomposeItemRequest";
  /** JWT令牌 */
  token: string;
  /** 目标物品ID */
  targetId: number;
}

/** 物品分解响应 {{Res:214}} */
export interface G2CDecomposeItemResponse {
  $type: "command.G2CDecomposeItemResponse";
  /** 分解获得的物品 */
  resultItems: ItemInfo[];
}

/** GM指令请求 {{Req:301}} */
export interface C2GGmCommandRequest {
  $type: "command.C2GGmCommandRequest";
  /** 令牌 */
  token: string;
  /** GM指令 */
  command: string;
  /** 参数列表 */
  params: string[];
}

/** GM指令响应 {{Res:302}} */
export interface G2CGmCommandResponse {
  $type: "command.G2CGmCommandResponse";
  /** 结果 */
  result: string;
  /** 消息 */
  message: string;
}

/** 获取装备信息请求 {{Req:401}} */
export interface C2GEquipInfoRequest {
  $type: "command.C2GEquipInfoRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取装备信息响应 {{Res:402}} */
export interface G2CEquipInfoResponse {
  $type: "command.G2CEquipInfoResponse";
  /** 已装备的物品列表 */
  equippedItems: ItemInfo[];
  /** 装备提供的战斗力 */
  combatPower: number;
}

/** 装备物品请求 {{Req:403}} */
export interface C2GEquipItemRequest {
  $type: "command.C2GEquipItemRequest";
  /** JWT令牌 */
  token: string;
  /** 物品所在背包类型 */
  bagType: number;
  /** 物品所在格子索引 */
  slotIndex: number;
  /** 装备位置 */
  equipSlot: number;
}

/** 装备物品响应 {{Res:404}} */
export interface G2CEquipItemResponse {
  $type: "command.G2CEquipItemResponse";
  /** 装备上的物品 */
  equippedItem?:
    | ItemInfo
    | undefined;
  /** 卸下的物品(如果有) */
  unequippedItem?:
    | ItemInfo
    | undefined;
  /** 战斗力变化 */
  combatPowerChange: number;
}

/** 卸下装备请求 {{Req:405}} */
export interface C2GUnequipItemRequest {
  $type: "command.C2GUnequipItemRequest";
  /** JWT令牌 */
  token: string;
  /** 装备位置 */
  equipSlot: number;
  /** 目标背包类型 */
  bagType: number;
  /** 目标格子索引(可选，0表示自动选择) */
  slotIndex: number;
}

/** 卸下装备响应 {{Res:406}} */
export interface G2CUnequipItemResponse {
  $type: "command.G2CUnequipItemResponse";
  /** 卸下的物品 */
  unequippedItem?:
    | ItemInfo
    | undefined;
  /** 战斗力变化 */
  combatPowerChange: number;
}

/** 随机获取装备请求 {{Req:407}} */
export interface C2GEquipRandomRequest {
  $type: "command.C2GEquipRandomRequest";
  /** JWT令牌 */
  token: string;
  /** 部位(0表示随机) */
  part: number;
  /** 是否替换现有装备 */
  isReplace: boolean;
}

/** 随机获取装备响应 {{Res:408}} */
export interface G2CEquipRandomResponse {
  $type: "command.G2CEquipRandomResponse";
  /** 新获得的装备 */
  newEquip?:
    | ItemInfo
    | undefined;
  /** 当前装备(如果有) */
  currentEquip?:
    | ItemInfo
    | undefined;
  /** 战力差异 */
  powerDiff: number;
}

/** 获取装备等级信息请求 {{Req:409}} */
export interface C2GEquipLevelInfoRequest {
  $type: "command.C2GEquipLevelInfoRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取装备等级信息响应 {{Res:410}} */
export interface G2CEquipLevelInfoResponse {
  $type: "command.G2CEquipLevelInfoResponse";
  /** 当前等级 */
  currentLevel: number;
  /** 最大等级 */
  maxLevel: number;
  /** 升级所需物品ID */
  itemId: number;
  /** 升级所需物品数量 */
  itemCount: number;
  /** 已拥有物品数量 */
  ownedCount: number;
  /** 升级所需时间(秒) */
  upgradeTime: number;
  /** 剩余时间(秒) */
  remainingTime: number;
  /** 是否正在升级 */
  isUpgrading: boolean;
  /** 当前等级品质概率 */
  currentOdds: number[];
  /** 下一等级品质概率 */
  nextOdds: number[];
}

/** 升级装备等级请求 {{Req:411}} */
export interface C2GEquipLevelUpgradeRequest {
  $type: "command.C2GEquipLevelUpgradeRequest";
  /** JWT令牌 */
  token: string;
  /** 是否使用广告加速 */
  useAd: boolean;
  /** 是否使用道具加速 */
  useItem: boolean;
  /** 加速道具ID */
  speedupItemId: number;
}

/** 升级装备等级响应 {{Res:412}} */
export interface G2CEquipLevelUpgradeResponse {
  $type: "command.G2CEquipLevelUpgradeResponse";
  /** 当前等级 */
  currentLevel: number;
  /** 剩余时间(秒) */
  remainingTime: number;
  /** 是否正在升级 */
  isUpgrading: boolean;
  /** 当前等级品质概率 */
  currentOdds: number[];
}

/** 装备过期推送 {{Push:451}} */
export interface G2CEquipmentExpiredPush {
  $type: "command.G2CEquipmentExpiredPush";
  /** 过期的装备列表 */
  expiredItems: ItemInfo[];
}

/** 装备等级升级完成通知 {{Push:452}} */
export interface G2CEquipmentLevelUpgradedPush {
  $type: "command.G2CEquipmentLevelUpgradedPush";
  /** 新等级 */
  newLevel: number;
}

/** 获取邮件列表请求 {{Req:501}} */
export interface C2GMailListRequest {
  $type: "command.C2GMailListRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取邮件列表响应 {{Res:502}} */
export interface G2CMailListResponse {
  $type: "command.G2CMailListResponse";
  /** 邮件列表 */
  mails: MailInfo[];
}

/** 读取邮件请求 {{Req:503}} */
export interface C2GReadMailRequest {
  $type: "command.C2GReadMailRequest";
  /** JWT令牌 */
  token: string;
  /** 邮件ID */
  mailId: bigint;
}

/** 读取邮件响应 {{Res:504}} */
export interface G2CReadMailResponse {
  $type: "command.G2CReadMailResponse";
  /** 邮件ID */
  mailId: bigint;
}

/** 领取邮件附件请求 {{Req:505}} */
export interface C2GClaimMailItemsRequest {
  $type: "command.C2GClaimMailItemsRequest";
  /** JWT令牌 */
  token: string;
  /** 邮件ID */
  mailId: bigint;
}

/** 领取邮件附件响应 {{Res:506}} */
export interface G2CClaimMailItemsResponse {
  $type: "command.G2CClaimMailItemsResponse";
  /** 邮件ID */
  mailId: bigint;
  /** 获得的物品 */
  items: ItemInfo[];
}

/** 删除邮件请求 {{Req:507}} */
export interface C2GDeleteMailRequest {
  $type: "command.C2GDeleteMailRequest";
  /** JWT令牌 */
  token: string;
  /** 邮件ID */
  mailId: bigint;
}

/** 删除邮件响应 {{Res:508}} */
export interface G2CDeleteMailResponse {
  $type: "command.G2CDeleteMailResponse";
  /** 邮件ID */
  mailId: bigint;
}

/** 新邮件推送 {{Push:551}} */
export interface G2CNewMailPush {
  $type: "command.G2CNewMailPush";
  /** 新邮件信息 */
  mail?: MailInfo | undefined;
}

/** 获取伙伴列表请求 {{Req:601}} */
export interface C2GPartnerListRequest {
  $type: "command.C2GPartnerListRequest";
  /** JWT令牌 */
  token: string;
}

/** 获取伙伴列表响应 {{Res:602}} */
export interface G2CPartnerListResponse {
  $type: "command.G2CPartnerListResponse";
  /** 伙伴列表 */
  partners: PartnerInfo[];
}

/** 伙伴升级请求 {{Req:603}} */
export interface C2GPartnerLevelUpRequest {
  $type: "command.C2GPartnerLevelUpRequest";
  /** JWT令牌 */
  token: string;
  /** 伙伴ID */
  partnerId: bigint;
}

/** 伙伴升级响应 {{Res:604}} */
export interface G2CPartnerLevelUpResponse {
  $type: "command.G2CPartnerLevelUpResponse";
  /** 更新后的伙伴信息 */
  partner?:
    | PartnerInfo
    | undefined;
  /** 属性增益 */
  propertyGains: PropertyChange[];
  /** 消耗的物品 */
  consumedItems: ItemInfo[];
}

/** 伙伴升星请求 {{Req:605}} */
export interface C2GPartnerStarUpRequest {
  $type: "command.C2GPartnerStarUpRequest";
  /** JWT令牌 */
  token: string;
  /** 伙伴ID */
  partnerId: bigint;
}

/** 伙伴升星响应 {{Res:606}} */
export interface G2CPartnerStarUpResponse {
  $type: "command.G2CPartnerStarUpResponse";
  /** 更新后的伙伴信息 */
  partner?:
    | PartnerInfo
    | undefined;
  /** 属性增益 */
  propertyGains: PropertyChange[];
  /** 消耗的物品 */
  consumedItems: ItemInfo[];
}

/** 伙伴解锁请求 {{Req:607}} */
export interface C2GPartnerUnlockRequest {
  $type: "command.C2GPartnerUnlockRequest";
  /** JWT令牌 */
  token: string;
  /** 单位ID */
  unitId: number;
}

/** 伙伴解锁响应 {{Res:608}} */
export interface G2CPartnerUnlockResponse {
  $type: "command.G2CPartnerUnlockResponse";
  /** 新解锁的伙伴信息 */
  partner?:
    | PartnerInfo
    | undefined;
  /** 消耗的碎片数量 */
  consumedFragments: number;
}

/** 伙伴属性变化推送 {{Push:651}} */
export interface G2CPartnerPropertyChangedPush {
  $type: "command.G2CPartnerPropertyChangedPush";
  /** 伙伴ID */
  partnerId: bigint;
  /** 属性变化 */
  propertyChanges: PropertyChange[];
  /** 变化原因 */
  reason: string;
}

export const C2LLoginRequest: MessageFns<C2LLoginRequest, "command.C2LLoginRequest"> = {
  $type: "command.C2LLoginRequest" as const,
};

export const L2CLoginResponse: MessageFns<L2CLoginResponse, "command.L2CLoginResponse"> = {
  $type: "command.L2CLoginResponse" as const,
};

export const C2GHeartbeatRequest: MessageFns<C2GHeartbeatRequest, "command.C2GHeartbeatRequest"> = {
  $type: "command.C2GHeartbeatRequest" as const,
};

export const G2CHeartbeatResponse: MessageFns<G2CHeartbeatResponse, "command.G2CHeartbeatResponse"> = {
  $type: "command.G2CHeartbeatResponse" as const,
};

export const C2GUserInfoRequest: MessageFns<C2GUserInfoRequest, "command.C2GUserInfoRequest"> = {
  $type: "command.C2GUserInfoRequest" as const,
};

export const G2CUserInfoResponse: MessageFns<G2CUserInfoResponse, "command.G2CUserInfoResponse"> = {
  $type: "command.G2CUserInfoResponse" as const,
};

export const C2GLoginGameRequest: MessageFns<C2GLoginGameRequest, "command.C2GLoginGameRequest"> = {
  $type: "command.C2GLoginGameRequest" as const,
};

export const G2CLoginGameResponse: MessageFns<G2CLoginGameResponse, "command.G2CLoginGameResponse"> = {
  $type: "command.G2CLoginGameResponse" as const,
};

export const C2GUserCardsRequest: MessageFns<C2GUserCardsRequest, "command.C2GUserCardsRequest"> = {
  $type: "command.C2GUserCardsRequest" as const,
};

export const G2CUserCardsResponse: MessageFns<G2CUserCardsResponse, "command.G2CUserCardsResponse"> = {
  $type: "command.G2CUserCardsResponse" as const,
};

export const C2GBagInfoRequest: MessageFns<C2GBagInfoRequest, "command.C2GBagInfoRequest"> = {
  $type: "command.C2GBagInfoRequest" as const,
};

export const G2CBagInfoResponse: MessageFns<G2CBagInfoResponse, "command.G2CBagInfoResponse"> = {
  $type: "command.G2CBagInfoResponse" as const,
};

export const C2GUseItemRequest: MessageFns<C2GUseItemRequest, "command.C2GUseItemRequest"> = {
  $type: "command.C2GUseItemRequest" as const,
};

export const G2CUseItemResponse: MessageFns<G2CUseItemResponse, "command.G2CUseItemResponse"> = {
  $type: "command.G2CUseItemResponse" as const,
};

export const C2GExpandBagRequest: MessageFns<C2GExpandBagRequest, "command.C2GExpandBagRequest"> = {
  $type: "command.C2GExpandBagRequest" as const,
};

export const G2CExpandBagResponse: MessageFns<G2CExpandBagResponse, "command.G2CExpandBagResponse"> = {
  $type: "command.G2CExpandBagResponse" as const,
};

export const C2GSortBagRequest: MessageFns<C2GSortBagRequest, "command.C2GSortBagRequest"> = {
  $type: "command.C2GSortBagRequest" as const,
};

export const G2CSortBagResponse: MessageFns<G2CSortBagResponse, "command.G2CSortBagResponse"> = {
  $type: "command.G2CSortBagResponse" as const,
};

export const C2GMoveItemRequest: MessageFns<C2GMoveItemRequest, "command.C2GMoveItemRequest"> = {
  $type: "command.C2GMoveItemRequest" as const,
};

export const G2CMoveItemResponse: MessageFns<G2CMoveItemResponse, "command.G2CMoveItemResponse"> = {
  $type: "command.G2CMoveItemResponse" as const,
};

export const C2GComposeItemRequest: MessageFns<C2GComposeItemRequest, "command.C2GComposeItemRequest"> = {
  $type: "command.C2GComposeItemRequest" as const,
};

export const G2CComposeItemResponse: MessageFns<G2CComposeItemResponse, "command.G2CComposeItemResponse"> = {
  $type: "command.G2CComposeItemResponse" as const,
};

export const C2GDecomposeItemRequest: MessageFns<C2GDecomposeItemRequest, "command.C2GDecomposeItemRequest"> = {
  $type: "command.C2GDecomposeItemRequest" as const,
};

export const G2CDecomposeItemResponse: MessageFns<G2CDecomposeItemResponse, "command.G2CDecomposeItemResponse"> = {
  $type: "command.G2CDecomposeItemResponse" as const,
};

export const C2GGmCommandRequest: MessageFns<C2GGmCommandRequest, "command.C2GGmCommandRequest"> = {
  $type: "command.C2GGmCommandRequest" as const,
};

export const G2CGmCommandResponse: MessageFns<G2CGmCommandResponse, "command.G2CGmCommandResponse"> = {
  $type: "command.G2CGmCommandResponse" as const,
};

export const C2GEquipInfoRequest: MessageFns<C2GEquipInfoRequest, "command.C2GEquipInfoRequest"> = {
  $type: "command.C2GEquipInfoRequest" as const,
};

export const G2CEquipInfoResponse: MessageFns<G2CEquipInfoResponse, "command.G2CEquipInfoResponse"> = {
  $type: "command.G2CEquipInfoResponse" as const,
};

export const C2GEquipItemRequest: MessageFns<C2GEquipItemRequest, "command.C2GEquipItemRequest"> = {
  $type: "command.C2GEquipItemRequest" as const,
};

export const G2CEquipItemResponse: MessageFns<G2CEquipItemResponse, "command.G2CEquipItemResponse"> = {
  $type: "command.G2CEquipItemResponse" as const,
};

export const C2GUnequipItemRequest: MessageFns<C2GUnequipItemRequest, "command.C2GUnequipItemRequest"> = {
  $type: "command.C2GUnequipItemRequest" as const,
};

export const G2CUnequipItemResponse: MessageFns<G2CUnequipItemResponse, "command.G2CUnequipItemResponse"> = {
  $type: "command.G2CUnequipItemResponse" as const,
};

export const C2GEquipRandomRequest: MessageFns<C2GEquipRandomRequest, "command.C2GEquipRandomRequest"> = {
  $type: "command.C2GEquipRandomRequest" as const,
};

export const G2CEquipRandomResponse: MessageFns<G2CEquipRandomResponse, "command.G2CEquipRandomResponse"> = {
  $type: "command.G2CEquipRandomResponse" as const,
};

export const C2GEquipLevelInfoRequest: MessageFns<C2GEquipLevelInfoRequest, "command.C2GEquipLevelInfoRequest"> = {
  $type: "command.C2GEquipLevelInfoRequest" as const,
};

export const G2CEquipLevelInfoResponse: MessageFns<G2CEquipLevelInfoResponse, "command.G2CEquipLevelInfoResponse"> = {
  $type: "command.G2CEquipLevelInfoResponse" as const,
};

export const C2GEquipLevelUpgradeRequest: MessageFns<
  C2GEquipLevelUpgradeRequest,
  "command.C2GEquipLevelUpgradeRequest"
> = { $type: "command.C2GEquipLevelUpgradeRequest" as const };

export const G2CEquipLevelUpgradeResponse: MessageFns<
  G2CEquipLevelUpgradeResponse,
  "command.G2CEquipLevelUpgradeResponse"
> = { $type: "command.G2CEquipLevelUpgradeResponse" as const };

export const G2CEquipmentExpiredPush: MessageFns<G2CEquipmentExpiredPush, "command.G2CEquipmentExpiredPush"> = {
  $type: "command.G2CEquipmentExpiredPush" as const,
};

export const G2CEquipmentLevelUpgradedPush: MessageFns<
  G2CEquipmentLevelUpgradedPush,
  "command.G2CEquipmentLevelUpgradedPush"
> = { $type: "command.G2CEquipmentLevelUpgradedPush" as const };

export const C2GMailListRequest: MessageFns<C2GMailListRequest, "command.C2GMailListRequest"> = {
  $type: "command.C2GMailListRequest" as const,
};

export const G2CMailListResponse: MessageFns<G2CMailListResponse, "command.G2CMailListResponse"> = {
  $type: "command.G2CMailListResponse" as const,
};

export const C2GReadMailRequest: MessageFns<C2GReadMailRequest, "command.C2GReadMailRequest"> = {
  $type: "command.C2GReadMailRequest" as const,
};

export const G2CReadMailResponse: MessageFns<G2CReadMailResponse, "command.G2CReadMailResponse"> = {
  $type: "command.G2CReadMailResponse" as const,
};

export const C2GClaimMailItemsRequest: MessageFns<C2GClaimMailItemsRequest, "command.C2GClaimMailItemsRequest"> = {
  $type: "command.C2GClaimMailItemsRequest" as const,
};

export const G2CClaimMailItemsResponse: MessageFns<G2CClaimMailItemsResponse, "command.G2CClaimMailItemsResponse"> = {
  $type: "command.G2CClaimMailItemsResponse" as const,
};

export const C2GDeleteMailRequest: MessageFns<C2GDeleteMailRequest, "command.C2GDeleteMailRequest"> = {
  $type: "command.C2GDeleteMailRequest" as const,
};

export const G2CDeleteMailResponse: MessageFns<G2CDeleteMailResponse, "command.G2CDeleteMailResponse"> = {
  $type: "command.G2CDeleteMailResponse" as const,
};

export const G2CNewMailPush: MessageFns<G2CNewMailPush, "command.G2CNewMailPush"> = {
  $type: "command.G2CNewMailPush" as const,
};

export const C2GPartnerListRequest: MessageFns<C2GPartnerListRequest, "command.C2GPartnerListRequest"> = {
  $type: "command.C2GPartnerListRequest" as const,
};

export const G2CPartnerListResponse: MessageFns<G2CPartnerListResponse, "command.G2CPartnerListResponse"> = {
  $type: "command.G2CPartnerListResponse" as const,
};

export const C2GPartnerLevelUpRequest: MessageFns<C2GPartnerLevelUpRequest, "command.C2GPartnerLevelUpRequest"> = {
  $type: "command.C2GPartnerLevelUpRequest" as const,
};

export const G2CPartnerLevelUpResponse: MessageFns<G2CPartnerLevelUpResponse, "command.G2CPartnerLevelUpResponse"> = {
  $type: "command.G2CPartnerLevelUpResponse" as const,
};

export const C2GPartnerStarUpRequest: MessageFns<C2GPartnerStarUpRequest, "command.C2GPartnerStarUpRequest"> = {
  $type: "command.C2GPartnerStarUpRequest" as const,
};

export const G2CPartnerStarUpResponse: MessageFns<G2CPartnerStarUpResponse, "command.G2CPartnerStarUpResponse"> = {
  $type: "command.G2CPartnerStarUpResponse" as const,
};

export const C2GPartnerUnlockRequest: MessageFns<C2GPartnerUnlockRequest, "command.C2GPartnerUnlockRequest"> = {
  $type: "command.C2GPartnerUnlockRequest" as const,
};

export const G2CPartnerUnlockResponse: MessageFns<G2CPartnerUnlockResponse, "command.G2CPartnerUnlockResponse"> = {
  $type: "command.G2CPartnerUnlockResponse" as const,
};

export const G2CPartnerPropertyChangedPush: MessageFns<
  G2CPartnerPropertyChangedPush,
  "command.G2CPartnerPropertyChangedPush"
> = { $type: "command.G2CPartnerPropertyChangedPush" as const };

export interface MessageFns<T, V extends string> {
  readonly $type: V;
}
