// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.5.0
// source: internal/service.proto

/* eslint-disable */

export const protobufPackage = "internal";

/** 服务状态同步 */
export interface ServiceStatus {
  $type: "internal.ServiceStatus";
  /** 节点名称 */
  nodeName: string;
  /** 服务类型(gate/game/etc) */
  serviceType: string;
  /** 服务地址 */
  host: string;
  /** 服务端口 */
  port: number;
  /** 当前连接数 */
  clientCount: number;
  /** 同步时间戳 */
  timestamp: bigint;
  /** 额外信息 */
  extra: { [key: string]: string };
}

export interface ServiceStatus_ExtraEntry {
  $type: "internal.ServiceStatus.ExtraEntry";
  key: string;
  value: string;
}

export const ServiceStatus: MessageFns<ServiceStatus, "internal.ServiceStatus"> = {
  $type: "internal.ServiceStatus" as const,
};

export const ServiceStatus_ExtraEntry: MessageFns<ServiceStatus_ExtraEntry, "internal.ServiceStatus.ExtraEntry"> = {
  $type: "internal.ServiceStatus.ExtraEntry" as const,
};

export interface MessageFns<T, V extends string> {
  readonly $type: V;
}
